"use strict";
const { test } = require("node:test"), assert = require("node:assert/strict");
const fs = require("fs"), os = require("os"), path = require("path"), crypto = require("crypto"), { EventEmitter } = require("events");
const { CompanionHub, registerCompanionIPC } = require("../../electron/companion-hub");
const { CompanionStore } = require("../../electron/companion-store");
const { validate, fill } = require("../../electron/companion-workflows");
const { baseURL } = require("../../electron/companion-connections");
function storage() { const key = crypto.randomBytes(32); return { isEncryptionAvailable: () => true,
 encryptString(s) { const iv=crypto.randomBytes(12), c=crypto.createCipheriv("aes-256-gcm",key,iv);return Buffer.concat([iv,c.update(s),c.final(),c.getAuthTag()]); },
 decryptString(b) { const c=crypto.createDecipheriv("aes-256-gcm",key,b.subarray(0,12)); c.setAuthTag(b.subarray(-16));return Buffer.concat([c.update(b.subarray(12,-16)),c.final()]).toString(); } }; }
function setup(t, extra={}) { const dir=fs.mkdtempSync(path.join(os.tmpdir(),"kai-hub-")), safeStorage=storage(); const options={dataDir:dir,safeStorage,privacyMode:()=>"local-first",models:()=>[{alias:"local",status:"ready"}],canUseModel:m=>m==="local",runLocal:async({prompt})=>"Summary: "+prompt,fetchImpl:async()=>new Response('{"result":"project data"}'),...extra};const hub=new CompanionHub(options);t.after(()=>{hub.stop();fs.rmSync(dir,{recursive:true,force:true});});return {hub,dir,options}; }
const conn = { name:"Fixture API",baseUrl:"https://fixture.example",auth:"bearer",secret:"synthetic-secret",allowAgent:true,allowSync:true,operations:[{id:"read",name:"Read",method:"GET",path:"/items/{item}"},{id:"write",name:"Write",method:"POST",path:"/items"}] };
const wf = steps => ({name:"Fixture routine",model:"local",schedule:{kind:"manual"},steps});
async function settle(hub,id) { for(let i=0;i<100;i++){if(!hub.workflows.active.has(id))return hub.workflows.get(id);await new Promise(r=>setTimeout(r,5));} throw new Error("Run did not settle"); }

test("Brain persists encrypted notes/goals, retrieves context, edits and deletes",t=>{const {hub,dir,options}=setup(t);const n=hub.store.note({title:"KAI project",text:"Mike wants a full AI companion",tags:"kai, kai, roadmap",category:"projects"});hub.store.goal({title:"Finish KAI companion",priority:"high"});assert.match(hub.store.context("KAI"),/full AI companion/);assert.equal(hub.store.search("nonsense").length,0);assert.deepEqual(n.tags,["kai","roadmap"]);hub.store.note({...n,text:"Updated companion scope"});const disk=fs.readFileSync(path.join(dir,"companion-hub.json"),"utf8");assert.ok(!disk.includes("Updated companion"));const reload=new CompanionStore(options);assert.match(reload.context("KAI"),/Updated companion/);hub.store.remove("notes",n.id);assert.equal(hub.store.data.notes.length,0);assert.match(hub.store.markdown(),/Finish KAI/);});
test("locked or corrupt encrypted store never overwrites saved bytes",t=>{const {hub,dir,options}=setup(t);hub.store.note({text:"Keep me"});const file=path.join(dir,"companion-hub.json"),before=fs.readFileSync(file);const locked=new CompanionStore({...options,safeStorage:storage()});assert.equal(locked.locked,true);assert.throws(()=>locked.note({text:"overwrite"}),/keychain/);assert.deepEqual(fs.readFileSync(file),before);const plain=new CompanionStore({...options,safeStorage:{...storage(),getSelectedStorageBackend:()=>"basic_text"}});assert.equal(plain.available(),false);});
test("source ingestion deduplicates, updates chunks and removes derived notes",t=>{const {hub}=setup(t);hub.importText("Plan.md","KAI project ".repeat(500));const count=hub.store.data.notes.length;assert.ok(count>1);assert.equal(hub.importText("Plan.md","KAI project ".repeat(500)).unchanged,true);assert.equal(hub.store.data.notes.length,count);hub.importText("Plan.md","New plan");assert.equal(hub.store.data.notes.length,1);const id=hub.store.data.sources[0].id;hub.store.remove("sources",id);assert.equal(hub.store.data.notes.length,0);assert.equal(hub.store.data.syncs.length,0);});
test("connection secrets never appear in status or API output, header auth persists",async t=>{let init;const {hub,dir}=setup(t,{fetchImpl:async(_u,i)=>{init=i;return new Response('{"echo":"synthetic-secret"}');}});const c=hub.connections.save(conn);assert.ok(!JSON.stringify(hub.status()).includes("synthetic-secret"));const out=await hub.connections.execute(hub.connections.prepare(c.id,"read",{item:"one"}));assert.ok(!out.includes("synthetic-secret"));assert.equal(init.headers.Authorization,"Bearer synthetic-secret");assert.equal(init.redirect,"error");assert.ok(!fs.readFileSync(path.join(dir,"companion-hub.json"),"utf8").includes("synthetic-secret"));});
test("destinations cannot inherit credentials; path inputs cannot escape base URL",t=>{const {hub}=setup(t);const c=hub.connections.save(conn);assert.throws(()=>hub.connections.save({...c,baseUrl:"https://other.example"}),/token/);assert.throws(()=>hub.connections.prepare(c.id,"read",{item:".."}),/value/);const r=hub.connections.prepare(c.id,"read",{item:"a/b?x=1"});assert.match(r.url,/a%2Fb%3Fx%3D1/);assert.throws(()=>baseURL("http://remote.example"),/HTTPS/);assert.throws(()=>baseURL("https://user:pass@remote.example"),/credentials/);assert.equal(baseURL("http://127.0.0.1:8123"),"http://127.0.0.1:8123");});
test("Local-Only blocks before HTTP; removal and revision changes invalidate requests",async t=>{let count=0;const {hub}=setup(t,{privacyMode:()=>"local-only",fetchImpl:async()=>{count++;return new Response("ok");}});const c=hub.connections.save(conn),r=hub.connections.prepare(c.id,"read",{item:"1"});await assert.rejects(hub.connections.execute(r),/Local-Only/);assert.equal(count,0);hub.connections.save({...c,secret:conn.secret,name:"Changed"});await assert.rejects(hub.connections.execute(r),/changed/);hub.connections.remove(c.id);await assert.rejects(hub.connections.execute(r),/changed/);});
test("connection responses are bounded and provider-level errors count as failure",async t=>{const {hub}=setup(t,{fetchImpl:async()=>new Response('{"ok":false,"error":"raw secret error"}')});const c=hub.connections.save(conn);await assert.rejects(hub.connections.execute(hub.connections.prepare(c.id,"read",{item:"1"})),/rejected/);hub.connections.fetch=async()=>new Response("x".repeat(200001));await assert.rejects(hub.connections.execute(hub.connections.prepare(c.id,"read",{item:"1"})),/too large/);});
test("source sync is opt-in and never accepts a write operation",async t=>{const {hub}=setup(t);const c=hub.connections.save(conn);assert.throws(()=>hub.source({name:"No",connectionId:c.id,operationId:"write"}),/GET/);const s=hub.source({name:"Project source",connectionId:c.id,operationId:"read",variables:{item:"1"},autoSync:true});await hub.sync(s.id);assert.match(hub.store.context("project"),/project data/);hub.connections.remove(c.id);assert.equal(hub.store.data.sources[0].autoSync,false);await assert.rejects(hub.sync(s.id),/background reads/);});
test("workflows checkpoint outputs, substitute inputs and stop on false conditions",async t=>{const {hub}=setup(t);const w=hub.workflows.save(wf([{type:"output",label:"Input",text:"{{input}}"},{type:"condition",text:"approved"},{type:"remember",label:"Must not save",text:"{{previous}}"}]));const id=hub.workflows.begin(w.id,"unmatched");const r=await settle(hub,id);assert.equal(r.status,"completed");assert.equal(r.steps.length,2);assert.equal(hub.store.data.notes.length,0);assert.deepEqual(fill({text:"{{previous}}",a:["{{input}}"]},{previous:'{"x":1}',input:"hello"}),{text:'{"x":1}',a:["hello"]});});
test("workflow writes park before dispatch, require resume, and cannot overlap",async t=>{let calls=0;const {hub}=setup(t,{fetchImpl:async()=>{calls++;return new Response("done");}});const c=hub.connections.save(conn),w=hub.workflows.save(wf([{type:"connection",connectionId:c.id,operationId:"write",body:{text:"{{input}}"}}]));const id=hub.workflows.begin(w.id,"hello");let r=await settle(hub,id);assert.equal(r.status,"waiting");assert.equal(calls,0);assert.equal(r.pending.body,'{"text":"hello"}');assert.throws(()=>hub.workflows.begin(w.id),/paused/);assert.throws(()=>hub.workflows.save({...w,name:"edit"}),/pending/);hub.workflows.resume(id);r=await settle(hub,id);assert.equal(r.status,"completed");assert.equal(calls,1);});
test("changed connections invalidate paused approvals and do not send",async t=>{let calls=0;const {hub}=setup(t,{fetchImpl:async()=>{calls++;return new Response("done");}});const c=hub.connections.save(conn),w=hub.workflows.save(wf([{type:"connection",connectionId:c.id,operationId:"write"}])),id=hub.workflows.begin(w.id);await settle(hub,id);hub.connections.save({...c,secret:conn.secret,name:"Changed"});hub.workflows.resume(id);const r=await settle(hub,id);assert.equal(r.status,"failed");assert.equal(calls,0);});
test("workflow restart never replays an uncertain external action",async t=>{const {hub,options}=setup(t);const w=hub.workflows.save(wf([{type:"approval",text:"Review"}])),id=hub.workflows.begin(w.id);await settle(hub,id);hub.workflows.patch(id,r=>{r.status="running";r.inFlight={type:"connection",index:0};});const reload=new CompanionHub(options);t.after(()=>reload.stop());assert.equal(reload.workflows.get(id).status,"interrupted");assert.throws(()=>reload.workflows.resume(id),/uncertain/);reload.workflows.cancel(id);assert.equal(reload.workflows.get(id).status,"cancelled");});
test("schedules advance once, drafts cannot run, and network/provider models are rejected",async t=>{const {hub}=setup(t);assert.throws(()=>validate({...wf([{type:"prompt",text:"hello"}]),model:"desktop:openai:example"}),/local model/);const draft=hub.workflows.save(wf([{type:"output",text:"draft"}]),{draft:true});assert.throws(()=>hub.workflows.begin(draft.id),/Review/);const w=hub.workflows.save({...wf([{type:"output",text:"scheduled"}]),schedule:{kind:"daily",hour:9},enabled:true});hub.store.change(d=>{d.workflows.find(x=>x.id===w.id).nextRunAt=new Date(0).toISOString();});await hub.workflows.tick();const r=hub.store.data.runs[0];await settle(hub,r.id);await hub.workflows.tick();assert.equal(hub.store.data.runs.length,1);assert.ok(Date.parse(hub.store.data.workflows.find(x=>x.id===w.id).nextRunAt)>Date.now());});
test("cancellation aborts in-flight inference and preserves a cancelled run",async t=>{let started;const ready=new Promise(r=>{started=r;});const {hub}=setup(t,{runLocal:({signal})=>new Promise((_resolve,reject)=>{started();signal.addEventListener("abort",()=>reject(new DOMException("Stopped","AbortError")));})});const w=hub.workflows.save(wf([{type:"prompt",text:"hello"}])),id=hub.workflows.begin(w.id);await ready;hub.workflows.cancel(id);const r=await settle(hub,id);assert.equal(r.status,"cancelled");});
test("private tools exclude network models and require real confirmation for notes and API calls",async t=>{const {hub}=setup(t);const c=hub.connections.save(conn);assert.deepEqual(hub.toolList("koinos-network"),[]);await assert.rejects(hub.tool("brain_remember",{text:"new note"},"local",async()=>false),/declined/);assert.equal(hub.store.data.notes.length,0);await hub.tool("brain_remember",{text:"new note"},"local",async()=>true);assert.equal(hub.store.data.notes.length,1);const name=hub.toolList("local").find(t=>t.name.startsWith("connection_")).name;await assert.rejects(hub.tool(name,{variables:{item:"1"}},"local",async()=>false),/declined/);});

test("IPC denies remote documents, subframes and mascot management; cancellation invalidates approval",async t=>{const {hub}=setup(t),handlers=new Map(),ipcMain={handle:(c,f)=>handlers.set(c,f),removeHandler:c=>handlers.delete(c)};
 function win(url,n){const wc=new EventEmitter();wc.id=n;wc.getURL=()=>url;wc.isDestroyed=()=>false;wc.mainFrame={url};const w=new EventEmitter();w.webContents=wc;w.isDestroyed=()=>false;w.isVisible=()=>true;return w;}
 const main=win("http://127.0.0.1:41100/",1),mascot=win("http://127.0.0.1:41100/mascot.html",2);let resolve;const ctl=registerCompanionIPC({ipcMain,service:hub,origin:"http://127.0.0.1:41100",getMainWindow:()=>main,getMascotWindow:()=>mascot,dialog:{showMessageBox:()=>new Promise(r=>{resolve=r;})}});t.after(()=>ctl.dispose());
 const event=w=>({sender:w.webContents,senderFrame:w.webContents.mainFrame});
 assert.equal((await handlers.get("companion:manage")(event(main),"status")).ok,true);
 await assert.rejects(handlers.get("companion:manage")(event(mascot),"status"),/denied/);
 await assert.rejects(handlers.get("companion:context")({...event(main),senderFrame:{url:"http://127.0.0.1:41100/"}},"local","hello"),/denied/);
 main.webContents.mainFrame.url="http://127.0.0.1:41100/other";await assert.rejects(handlers.get("companion:manage")(event(main),"status"),/denied/);main.webContents.mainFrame.url="http://127.0.0.1:41100/";
 const pending=handlers.get("companion:tool")(event(main),"brain_remember",{text:"do not save"},"local");await new Promise(r=>setImmediate(r));await handlers.get("companion:cancel")(event(main));resolve({response:1});const result=await pending;assert.equal(result.ok,false);assert.equal(hub.store.data.notes.length,0);
});

test("renderer private context protects routing and never gives worker models Brain notes", async () => {
 const vm=require("vm"),calls=[];const window={kaiCompanionBridge:{context:async model=>({ok:true,result:{eligible:model==="local",context:model==="local"?"Private fixture memory":""}})}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,"../../ui/companion-client.js"),"utf8"),{window,DOMException});
 const body={model:"local",stream:true,messages:[{role:"user",content:"hello"}]};const out=await window.KaiCompanionClient.enrich(body);assert.equal(out.kai_private_desktop,true);assert.equal(out.messages[0].content,"Private fixture memory");assert.equal(body.messages.length,1);
 const network=await window.KaiCompanionClient.enrich({...body,model:"koinos-network"});assert.equal(network.kai_private_desktop,undefined);assert.equal(network.messages.length,1);
 const planning=await window.KaiCompanionClient.enrich({...body,stream:false});assert.equal(planning.messages.length,1);assert.equal(planning.kai_private_desktop,true);
});
test("private tool observations cannot be forwarded through ordinary web or Core tools", async () => {
 const vm=require("vm");let coreCalls=0,privateCalls=0;const window={kaiCompanionBridge:{tools:async()=>({ok:true,result:[{name:"brain_search"}]}),tool:async()=>{privateCalls++;return {ok:true,result:"private data"};},cancel:async()=>({ok:true})}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,"../../ui/companion-client.js"),"utf8"),{window,DOMException});
 const json=window.KaiCompanionClient.toolJSON("local",async url=>{coreCalls++;return url==="/core/tools"?{tools:[{name:"web_search"}]}:{ok:true,result:"public"};});
 const list=await json("/core/tools");assert.equal(list.tools.length,2);
 await json("/core/tools/call",{body:JSON.stringify({name:"brain_search",args:{query:"KAI"}})});assert.equal(privateCalls,1);
 await assert.rejects(json("/core/tools/call",{body:JSON.stringify({name:"web_search",args:{query:"private data"}})}),/Private Brain/);assert.equal(coreCalls,1);
});
test("renderer brackets private tools so voice and listening cannot overlap native review", async () => {
 const vm=require("vm"),events=[];const window={kaiCompanionBridge:{tools:async()=>({ok:true,result:[{name:"brain_search"}]}),tool:async()=>({ok:true,result:"private data"}),cancel:async()=>({ok:true})}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,"../../ui/companion-client.js"),"utf8"),{window,DOMException});
 const json=window.KaiCompanionClient.toolJSON("local",async url=>url==="/core/tools"?{tools:[]}:{ok:true},new AbortController().signal,{onPrivateTool:(active,name)=>events.push([active,name])});
 await json("/core/tools");await json("/core/tools/call",{body:JSON.stringify({name:"brain_search",args:{query:"KAI"}})});
 assert.deepEqual(events,[[true,"brain_search"],[false,"brain_search"]]);
});
