"use strict";
const {test}=require("node:test"),assert=require("node:assert/strict"),fs=require("fs"),os=require("os"),path=require("path"),crypto=require("crypto");
const {ComposioClient,tool,validateArgs,connectURL}=require("../lib/composio-client");
const {CompanionHub}=require("../../electron/companion-hub"),{fixture,TOOLS}=require("./fixtures/composio");
function setup(t,extra={}) {
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),"kai-composio-")),f=fixture(),key=crypto.randomBytes(32);
 const safeStorage={isEncryptionAvailable:()=>true,encryptString:s=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv("aes-256-gcm",key,iv);return Buffer.concat([iv,c.update(s),c.final(),c.getAuthTag()]);},decryptString:b=>{const c=crypto.createDecipheriv("aes-256-gcm",key,b.subarray(0,12));c.setAuthTag(b.subarray(-16));return Buffer.concat([c.update(b.subarray(12,-16)),c.final()]).toString();}};
 const hub=new CompanionHub({dataDir:dir,safeStorage,privacyMode:()=>"local-first",models:()=>[{alias:"local",status:"ready"}],canUseModel:m=>m==="local",runLocal:async()=>"summary",fetchImpl:f.fetch,openExternal:async()=>{},...extra});
 t.after(()=>{hub.stop();fs.rmSync(dir,{recursive:true,force:true});});return {hub,f,dir,safeStorage};
}
async function connected(hub,f){await hub.composio.save({mode:"personal",key:f.key});await hub.composio.connect("github");f.authorize();await hub.composio.refresh();const c=hub.connections.list()[0];await hub.composio.permissions({id:c.id,name:"My GitHub",tools:["GITHUB_LIST_ISSUES"],allowAgent:true,allowSync:true});return hub.connections.list()[0];}
test("Composio catalog uses real category IDs; account responses strip credentials and other users",async()=>{const f=fixture(),api=new ComposioClient({key:f.key,fetchImpl:f.fetch});const list=await api.catalog({category:"developer-tools",search:"git"});assert.equal(list.items[0].slug,"github");assert.equal(list.categories[0].id,"developer-tools");await api.connect("github","alice");await api.connect("github","bob");const accounts=await api.accounts("alice");assert.equal(accounts.length,1);assert.ok(!JSON.stringify(accounts).includes("provider-secret"));await assert.rejects(api.disconnect(accounts[0].id,"bob"),/different account/);await assert.rejects(api.execute({id:accounts[0].id,tool:"GITHUB_LIST_ISSUES",arguments:{}},"bob"),/different account/);assert.equal(f.accounts.length,2);});
test("Composio action safety follows metadata, validates inputs, pins execution and rejects cross-app actions",async()=>{assert.equal(tool({...TOOLS[0],tags:[]}).readOnly,false);assert.throws(()=>validateArgs({owner:"x",repo:"y",limit:1.5},tool(TOOLS[0]).schema),/Check/);assert.throws(()=>validateArgs({owner:"x",repo:"y",redirect_url:"https://elsewhere"},tool(TOOLS[0]).schema),/Unknown/);assert.throws(()=>connectURL("https://connect.composio.dev.evil.test/link"),/unsupported/);assert.throws(()=>connectURL("https://user:pass@connect.composio.dev/link"),/unsupported/);const f=fixture(),api=new ComposioClient({key:f.key,fetchImpl:f.fetch});const a=await api.connect("github","alice");f.authorize();await assert.rejects(api.execute({id:a.id,tool:"GMAIL_LIST_MESSAGES",arguments:{}},"alice"),/does not belong/);const out=await api.execute({id:a.id,tool:"GITHUB_LIST_ISSUES",version:"20260901_00",arguments:{owner:"alice",repo:"kai"}},"alice");assert.ok(!out.includes(f.key));assert.equal(f.executions[0].version,"20260901_00");assert.equal(f.executions[0].connected_account_id,a.id);});
test("personal key is encrypted and never exported; selected reads feed Brain and preserve custom APIs",async t=>{const {hub,f,dir}=setup(t),c=await connected(hub,f);assert.ok(!JSON.stringify(hub.status()).includes(f.key));assert.ok(!fs.readFileSync(path.join(dir,"companion-hub.json"),"utf8").includes(f.key));assert.equal(hub.toolList("network").length,0);const source=hub.source({name:"KAI issues",connectionId:c.id,operationId:"GITHUB_LIST_ISSUES",variables:{owner:"alice",repo:"kai"},autoSync:true});await hub.sync(source.id);assert.match(hub.store.context("KAI"),/Plan KAI/);const direct=hub.connections.save({name:"Local API",baseUrl:"http://127.0.0.1:8123",auth:"none",operations:[{id:"read",method:"GET",path:"/status"}]});await hub.composio.disconnect(c.id);assert.equal(hub.store.data.sources[0].autoSync,false);assert.equal(hub.connections.list()[0].id,direct.id);assert.equal(f.accounts.length,0);});
test("a second sign-in never claims the existing account, including links without an account ID",async t=>{const {hub,f}=setup(t);await connected(hub,f);f.withLinkId=false;await hub.composio.connect("github");await hub.composio.refresh();assert.ok(hub.composio.status().pending);assert.equal(hub.composio.status().completed,null);f.authorize();await hub.composio.refresh();assert.equal(hub.composio.status().completed.accountId,"ca_2");assert.equal(hub.connections.list().length,2);await hub.composio.connect("github");hub.composio.pending.expiresAt=0;await hub.composio.refresh();assert.equal(hub.composio.status().completed,null);});
test("mode changes invalidate reviewed actions and stale sources; switching back preserves grants",async t=>{const {hub,f}=setup(t),c=await connected(hub,f),r=hub.connections.prepare(c.id,"GITHUB_LIST_ISSUES",{owner:"alice",repo:"kai"});await hub.composio.save({mode:"managed"});assert.equal(hub.connections.list().length,0);await assert.rejects(hub.connections.execute(r),/changed/);await hub.composio.save({mode:"personal"});assert.equal(hub.connections.list()[0].operations.length,1);await hub.composio.permissions({id:c.id,tools:[],allowSync:false});await assert.rejects(hub.connections.execute(r),/changed/);});
test("Local-Only blocks catalog, browser opening and in-flight HTTP before results reach Brain",async t=>{let mode="local-first",opened=0;const {hub,f}=setup(t,{privacyMode:()=>mode,openExternal:async()=>{opened++;}});await connected(hub,f);await hub.composio.connect("github");const count=f.calls.length;mode="local-only";await assert.rejects(hub.composio.catalog({}),/Local-Only/);await assert.rejects(hub.composio.reopen(),/Local-Only/);assert.equal(f.calls.length,count);assert.equal(opened,2);mode="local-first";hub.composio.clients.clear();hub.composio.fetch=async(_u,init)=>new Promise((_resolve,reject)=>{const socket=setTimeout(()=>reject(new Error("fixture timed out")),5000);init.signal.addEventListener("abort",()=>{clearTimeout(socket);reject(init.signal.reason);},{once:true});});const pending=hub.composio.catalog({});mode="local-only";await assert.rejects(pending,/stopped/);});
test("writes need a separate grant and cannot become background Brain sources",async t=>{const {hub,f}=setup(t),c=await connected(hub,f);await assert.rejects(hub.composio.permissions({id:c.id,tools:["GITHUB_CREATE_ISSUE"]}),/reviewed actions/);await hub.composio.permissions({id:c.id,tools:["GITHUB_CREATE_ISSUE"],allowWrite:true,allowSync:true,allowAgent:true});assert.throws(()=>hub.source({name:"Unsafe",connectionId:c.id,operationId:"GITHUB_CREATE_ISSUE",variables:{title:"test"}}),/GET/);let reviews=0;await assert.rejects(hub.tool("connection_"+c.id.replace(/-/g,"")+"_GITHUB_CREATE_ISSUE",{variables:{title:"test"}},"local",async()=>{reviews++;return false;}),/declined/);assert.equal(reviews,1);assert.equal(f.executions.length,0);});
test("managed requests use KAI authentication without accepting a caller user ID or returning the key",async t=>{let token="session-a",calls=[];const {hub}=setup(t,{account:{origin:()=>"https://kai.example",_token:()=>token},fetchImpl:async(url,init={})=>{calls.push({url,init});return new Response(JSON.stringify(url.endsWith("/status")?{available:true,protocol:1,generation:"project-a"}:{ok:true,result:{userId:"kai:alice",accounts:[{id:"ca_managed",toolkit:"github",status:"ACTIVE",name:"Work"}]}}));}});await hub.composio.refresh();assert.equal(hub.connections.list().length,1);assert.equal(calls[1].init.headers.authorization,"Bearer session-a");assert.equal(JSON.parse(calls[1].init.body).userId,undefined);token="session-b";assert.equal(hub.connections.list().length,0);assert.ok(!JSON.stringify(hub.status()).includes("session-a"));});

test("existing enabled auth configs are reused without exposing their credentials",async()=>{const f=fixture();let created=0;const api=new ComposioClient({key:f.key,fetchImpl:async(url,init)=>{if(new URL(url).pathname.endsWith("/auth_configs")){if(init.method==="POST")created++;else return new Response(JSON.stringify({items:[{id:"ac_github",toolkit:{slug:"github"},status:"ENABLED",is_composio_managed:false,credentials:{client_secret:"do-not-export"}}]}));}return f.fetch(url,init);}});const r=await api.connect("github","alice");assert.equal(created,0);assert.ok(!JSON.stringify(r).includes("do-not-export"));assert.equal(f.links[0].user_id,"alice");});

test("curated reads require the exact documented version; changed or explicit unsafe metadata requires review",()=>{const raw={...TOOLS[0],slug:"GITHUB_LIST_REPOSITORY_ISSUES",version:"20260902_00",tags:[]};assert.equal(tool(raw).readOnly,true);assert.equal(tool({...raw,version:"20260910_00"}).readOnly,false);assert.equal(tool({...raw,annotations:{readOnlyHint:false}}).readOnly,false);assert.equal(tool({...raw,slug:"GITHUB_CREATE_AN_ISSUE"}).readOnly,false);});
