"use strict";
const { test } = require("node:test"), assert = require("node:assert/strict"), fs = require("fs"), os = require("os"), path = require("path"), crypto = require("crypto");
const { CompanionHub } = require("../../electron/companion-hub"), M = require("../../ui/workflow-model"), V = require("../../electron/workflow-values"), { next } = require("../../electron/workflow-schedules");
function setup(t, overrides = {}) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "kai-graph-")), key = crypto.randomBytes(32), iv = crypto.randomBytes(16);
  const safeStorage = { isEncryptionAvailable: () => true, encryptString: s => { const c = crypto.createCipheriv("aes-256-cbc", key, iv); return Buffer.concat([c.update(s), c.final()]); }, decryptString: b => { const c = crypto.createDecipheriv("aes-256-cbc", key, iv); return Buffer.concat([c.update(b), c.final()]).toString(); } };
  const opts = { dataDir: dir, safeStorage, privacyMode: () => "local-first", models: () => [{ alias: "local", status: "ready" }], canUseModel: () => true, runLocal: async ({ prompt }) => "Answer: " + prompt, lookup: async () => [{ address: "93.184.216.34", family: 4 }], fetchImpl: async () => new Response('{"ok":true}'), ...overrides };
  const hub = new CompanionHub(opts); t.after(() => { hub.stop(); fs.rmSync(dir, { recursive: true, force: true }); }); return { hub, opts, dir };
}
const node = (type, id, config = {}) => M.node(type, id, undefined, config, id), edge = M.edge;
const spec = (nodes, edges) => ({ name: "Test graph", model: "local", graph: { version: 2, nodes: [node("trigger", "start"), ...nodes], edges } });
async function settle(hub, id) { for (let i = 0; i < 300; i++) { if (!hub.workflows.active.has(id)) return hub.workflows.get(id); await new Promise(r => setTimeout(r, 10)); } throw Error("Run did not settle"); }
async function run(hub, w, input) { return settle(hub, hub.workflows.begin(hub.workflows.save(w).id, input)); }
const conn = { name: "API", baseUrl: "https://api.example.com", auth: "none", allowSync: true, enabled: true, operations: [{ id: "read", method: "GET", path: "/read", name: "Read" }, { id: "write", method: "POST", path: "/write", name: "Write" }] };
test("graph routes true/false items independently and merge waits for skipped branches", async t => {
  const { hub } = setup(t); const w = spec([node("condition", "check", { expression: "=item.score", operator: "greater", value: 4 }), node("transform", "yes", { set: { result: "=item.id" } }), node("transform", "no", { set: { ignored: "=item.id" } }), node("merge", "join")], [edge("start", "check"), edge("check", "yes", "true"), edge("check", "no", "false"), edge("yes", "join", "main", "A"), edge("no", "join", "main", "B")]);
  const result = await run(hub, w, [{ id: "high", score: 9 }, { id: "low", score: 1 }]); assert.equal(result.status, "completed", result.error); assert.deepEqual(result.output.map(x => x.result || x.ignored), ["high", "low"]);
  const single = await run(hub, { ...w, name: "One branch" }, [{ id: "only", score: 9 }]); assert.equal(single.frames.root.states.no.status, "skipped"); assert.equal(single.output.length, 1);
});
test("fan-out overlaps independent local nodes and emits an ordered merge", async t => {
  let active = 0, peak = 0; const { hub } = setup(t, { runLocal: async ({ prompt }) => { peak = Math.max(peak, ++active); await new Promise(r => setTimeout(r, 30)); active--; return prompt; } });
  const result = await run(hub, spec([node("agent", "a", { prompt: "first" }), node("agent", "b", { prompt: "second" }), node("merge", "join")], [edge("start", "a"), edge("start", "b"), edge("a", "join", "main", "A"), edge("b", "join", "main", "B")]), "go"); assert.equal(peak, 2); assert.equal(result.status, "completed", result.error); assert.match(result.output[0].text, /first/); assert.match(result.output[1].text, /second/);
});
test("bounded loops carry updated items into Done and survive a nested approval", async t => {
  const { hub, opts } = setup(t); const w = hub.workflows.save(spec([node("loop", "repeat", { maxIterations: 3, condition: "=item.count < 2", onExceeded: "continue" }), node("transform", "add", { set: { count: "=item.count + 1" } }), node("approval", "review", { text: "Review iteration {{previous}}" }), node("output", "done", { text: "" })], [edge("start", "repeat"), edge("repeat", "add", "body"), edge("add", "review"), edge("review", "repeat", "approved"), edge("repeat", "done", "done")]));
  const id = hub.workflows.begin(w.id, { count: 0 }); let r = await settle(hub, id); assert.equal(r.status, "waiting", r.error); assert.equal(r.inFlight, null);
  const reload = new CompanionHub(opts); t.after(() => reload.stop()); reload.workflows.resume(id); r = await settle(reload, id); assert.equal(r.status, "waiting", r.error); reload.workflows.resume(id); r = await settle(reload, id); assert.equal(r.status, "completed", r.error); assert.equal(r.output[0].count, 2); assert.equal(r.steps.filter(s => s.nodeId === "add").length, 2);
});
test("sub-workflow uses a snapshot and preserves nested human rejection", async t => {
  const { hub } = setup(t); const child = hub.workflows.save(spec([node("approval", "review"), node("output", "approved", { text: "yes" }), node("output", "rejected", { text: "no" })], [edge("start", "review"), edge("review", "approved", "approved"), edge("review", "rejected", "rejected")]));
  const parent = hub.workflows.save(spec([node("sub_workflow", "child", { workflowId: child.id })], [edge("start", "child")])); const id = hub.workflows.begin(parent.id, "input"); let r = await settle(hub, id); assert.equal(r.status, "waiting", r.error); hub.workflows.decide(id, "rejected"); r = await settle(hub, id); assert.equal(r.status, "completed", r.error); assert.equal(r.output[0].text, "no");
});
test("per-item external writes pause separately and never replay completed items", async t => {
  const sent = []; const { hub } = setup(t, { fetchImpl: async (_url, req) => { sent.push(JSON.parse(req.body)); return new Response("sent"); } }); const c = hub.connections.save(conn);
  const w = hub.workflows.save(spec([node("tool_call", "send", { connectionId: c.id, operationId: "write", body: { id: "=item.id" }, execution: "per_item" })], [edge("start", "send")])); const id = hub.workflows.begin(w.id, [{ id: 1 }, { id: 2 }]);
  let r = await settle(hub, id); assert.equal(r.status, "waiting"); assert.equal(sent.length, 0); hub.workflows.resume(id); r = await settle(hub, id); assert.equal(r.status, "waiting", r.error); assert.deepEqual(sent, [{ id: 1 }]); hub.workflows.resume(id); r = await settle(hub, id); assert.equal(r.status, "completed", r.error); assert.deepEqual(sent, [{ id: 1 }, { id: 2 }]);
});
test("changed connections invalidate a graph approval without dispatching", async t => {
  let calls = 0; const { hub } = setup(t, { fetchImpl: async () => { calls++; return new Response("sent"); } }); const c = hub.connections.save(conn); const w = hub.workflows.save(spec([node("tool_call", "write", { connectionId: c.id, operationId: "write" })], [edge("start", "write")])); const id = hub.workflows.begin(w.id, "x"); await settle(hub, id); hub.connections.save({ ...c, name: "Changed" }); hub.workflows.resume(id); const r = await settle(hub, id); assert.equal(r.status, "failed"); assert.equal(calls, 0);
});
test("read retry and error-port recovery retain failure details", async t => {
  let calls = 0; const { hub } = setup(t, { fetchImpl: async () => { calls++; throw new Error("offline"); } }); const c = hub.connections.save(conn);
  const r = await run(hub, spec([node("tool_call", "read", { connectionId: c.id, operationId: "read", retries: 1, onError: "route" }), node("output", "recover", { text: "Recovered from {{previous}}" })], [edge("start", "read"), edge("read", "recover", "error")]), "x"); assert.equal(calls, 2); assert.equal(r.status, "completed", r.error); assert.equal(r.steps.find(s => s.nodeId === "read").status, "failed"); assert.match(r.output[0].text, /Recovered/);
});
test("split, mapping, parsing and dedup preserve typed data across runs", async t => {
  const { hub } = setup(t); const w = hub.workflows.save(spec([node("split_out", "split", { field: "=item.list" }), node("dedup", "unique", { key: "=item.id" }), node("transform", "map", { set: { id: "=item.id", upper: "=item.title.toUpperCase()" }, keepFields: false })], [edge("start", "split"), edge("split", "unique"), edge("unique", "map")]));
  const first = await settle(hub, hub.workflows.begin(w.id, { list: [{ id: "a", title: "hello" }, { id: "a", title: "dup" }] })); assert.equal(first.status, "completed", first.error); assert.deepEqual(first.output, [{ id: "a", upper: "HELLO" }]); const second = await settle(hub, hub.workflows.begin(w.id, { list: [{ id: "a", title: "hello" }, { id: "b", title: "new" }] })); assert.deepEqual(second.output, [{ id: "b", upper: "NEW" }]); assert.deepEqual(V.parseOutput('name,note\nAda,"a,b"', "csv"), [{ name: "Ada", note: "a,b" }]);
});
test("isolated code cannot read host globals or run forever", async () => {
  const scope = { item: { n: 4 }, items: [{ n: 4 }], input: "x", nodes: {}, iteration: 0 };
  assert.deepEqual(await V.evaluate("return items.map(x => ({n:x.n*2}));", scope, undefined, false), [{ n: 8 }]); assert.equal(await V.evaluate("typeof process + ':' + typeof require + ':' + typeof fetch", scope), "undefined:undefined:undefined"); await assert.rejects(V.evaluate("while(true){}", scope, undefined, false), /failed|interrupt/); await assert.rejects(V.evaluate("return 'x'.repeat(300000);", scope, undefined, false), /200 KB/);
});
test("cron schedules respect time zones and one-shot dates do not catch up repeatedly", () => { assert.equal(next({ kind: "cron", expression: "30 9 * * 1-5", timezone: "America/New_York" }, Date.parse("2026-09-09T10:00:00Z")), "2026-09-09T13:30:00.000Z"); assert.equal(next({ kind: "at", at: "2026-01-01T00:00:00Z" }), null); assert.throws(() => next({ kind: "cron", expression: "* * * * * *" }), /five-field/); });
test("drafts may preserve unfinished nodes but cannot be enabled or executed", t => { const { hub } = setup(t); const draft = hub.workflows.save(spec([node("tool_call", "unset")], []), { draft: true }); assert.equal(draft.draft, true); assert.throws(() => hub.workflows.begin(draft.id), /Review/); assert.throws(() => hub.workflows.setEnabled(draft.id, true), /Review/); assert.throws(() => hub.workflows.save(draft), /Connect|Choose/); });
test("graph validation rejects uncontrolled cycles and recursive sub-workflows", t => { const { hub } = setup(t); assert.throws(() => hub.workflows.save(spec([node("transform", "a"), node("transform", "b")], [edge("start", "a"), edge("a", "b"), edge("b", "a")])), /Loop/); const w = hub.workflows.save(spec([node("output", "a")], [edge("start", "a")])); assert.throws(() => hub.workflows.save({ ...w, graph: { ...w.graph, nodes: [node("trigger", "start"), node("sub_workflow", "a", { workflowId: w.id })] } }), /itself/); });
test("legacy task migration is durable, idempotent and preserves chat history", t => { const { TaskRunner } = require("../lib/tasks"); const dir = fs.mkdtempSync(path.join(os.tmpdir(), "kai-old-tasks-")); t.after(() => fs.rmSync(dir, { recursive: true, force: true })); const tasks = new TaskRunner({ file: path.join(dir, "tasks.json"), chats: {}, runChat: async () => "" }); const old = tasks.create({ name: "Morning", prompt: "Brief me", model: "local", schedule: { kind: "daily", hour: 7 } }); old.lastChatId = "old-chat"; const { hub } = setup(t, { legacyTasks: tasks }); hub.workflows.migrateTasks(); hub.workflows.migrateTasks(); assert.equal(hub.store.data.workflows.length, 1); const w = hub.store.data.workflows[0]; assert.equal(w.legacyTask.lastChatId, "old-chat"); assert.equal(w.nextRunAt, old.nextRunAt); assert.equal(tasks.list()[0].enabled, false); assert.equal(tasks.list()[0].migratedWorkflowId, w.id); assert.throws(() => tasks.update(old.id, { enabled: true }), /Workflows/); });
test("app-change watches establish a baseline, then run once per change", async t => { let value = 1; const { hub } = setup(t, { fetchImpl: async () => new Response(JSON.stringify({ value })) }); const c = hub.connections.save(conn), w = spec([node("output", "result", { text: "{{previous}}" })], [edge("start", "result")]); w.enabled = true; w.graph.nodes[0].config = { kind: "app_change", connectionId: c.id, operationId: "read", intervalMinutes: 1 }; hub.workflows.save(w); const now = Date.now(); await hub.workflows.tick(now); assert.equal(hub.store.data.runs.length, 0); value = 2; await hub.workflows.tick(now + 61000); await settle(hub, hub.store.data.runs[0].id); assert.equal(hub.store.data.runs.length, 1); await hub.workflows.tick(now + 122000); assert.equal(hub.store.data.runs.length, 1); });
