'use strict';
const fs = require('node:fs'), path = require('node:path');
const { languages } = require('../ui/i18n');
const dir = path.join(__dirname, '../ui/locales');
const catalogs = {};
for (const { code } of languages.filter(l => l.code !== 'en')) catalogs[code] = JSON.parse(fs.readFileSync(path.join(dir, code + '.json'), 'utf8'));
const keys = Object.keys(catalogs.es).sort();
for (const [code, table] of Object.entries(catalogs)) {
  if (JSON.stringify(Object.keys(table).sort()) !== JSON.stringify(keys)) throw new Error('Catalog key mismatch: ' + code);
  for (const [key, value] of Object.entries(table)) {
    if (typeof value !== 'string' || !value.trim()) throw new Error('Empty translation: ' + code + ': ' + key);
    const slots = text => JSON.stringify((text.match(/\{\d+\}/g) || []).sort());
    if (slots(key) !== slots(value)) throw new Error('Placeholder mismatch: ' + code + ': ' + key);
  }
}
const output = '/* Generated by scripts/build-locales.js from the JSON catalogs. */\n(function(root) { root.KaiLocaleCatalogs = ' + JSON.stringify(catalogs) + '; })(typeof window === "object" ? window : globalThis);\n';
if (process.argv.includes('--check')) {
  if (fs.readFileSync(path.join(dir, 'catalogs.js'), 'utf8') !== output) throw new Error('Run node scripts/build-locales.js');
} else fs.writeFileSync(path.join(dir, 'catalogs.js'), output);
console.log(`${languages.length} languages; ${keys.length} translated messages per catalog.`);
