"use strict";
(() => {
  const root = () => document.getElementById("view-agents"), bridge = window.kaiCompanionBridge;
  const esc = v => String(v ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
  const call = (action, input = {}) => window.KaiCompanionClient.checked(bridge.manage("agentNetwork" + action, input));
  const btn = (label, action, id = "", cls = "", role = "") => `<button type="button" class="${cls}" data-an="${action}" data-id="${esc(id)}" data-role="${role}">${esc(label)}</button>`;
  const field = (label, content) => `<label class="an-field"><span>${label}</span>${content}</label>`;
  const input = (name, value = "", placeholder = "") => `<input type="text" name="${name}" value="${esc(value)}" placeholder="${esc(placeholder)}">`;
  const area = (name, value = "", rows = 5) => `<textarea name="${name}" rows="${rows}">${esc(value)}</textarea>`;
  const option = (value, label, selected) => `<option value="${esc(value)}" ${value === selected ? "selected" : ""}>${esc(label)}</option>`;
  const date = n => new Date(n).toLocaleString([], { dateStyle: "medium", timeStyle: "short" });
  let state, tab = "discover", editor = null, selection = null, timer, busy = false, workflows = [], search = "";
  const tabs = [["discover", "Discover"], ["mine", "My agents"], ["jobs", "Jobs"], ["earnings", "Earnings"], ["activity", "Activity"], ["settings", "Network settings"]];
  function notice(message, error = false) { const n = root()?.querySelector(".an-notice"); if (n) { n.textContent = message; n.classList.toggle("error", error); } }
  async function refresh() { state = await call("Status"); }
  function empty(title, text, action = "") { return `<div class="an-empty"><span class="an-orbit" aria-hidden="true">✧</span><h2>${title}</h2><p>${text}</p>${action}</div>`; }
  function draw() {
    const out = root(); if (!out) return;
    out.innerHTML = `<div class="an-notice" role="status" aria-live="polite"></div><div class="hub-shell an-shell"><nav class="hub-rail" aria-label="Agent Network sections"><div class="hub-rail-label">Agent Network</div>${tabs.map(([key, label]) => btn(label, "tab", key, tab === key ? "active" : "")).join("")}</nav><main class="hub-content an-content"></main></div>`;
    const main = out.querySelector("main");
    if (!bridge) { main.innerHTML = empty("Open KAI on your desktop", "Agent Network uses your private desktop installation."); return; }
    if (!state) return;
    if (!state.enabled && tab !== "settings") { main.innerHTML = empty("Give your agents a place to work", "Create a service from a workflow, test it privately, and connect with other independently hosted agents.", btn("Set up Agent Network", "tab", "settings", "primary")) + `<p class="an-footnote">Private service preview. Paid KAI services require the new testnet contracts and release checks.</p>`; return; }
    if (editor) { main.innerHTML = editorHTML(); return; }
    if (tab === "settings") { main.innerHTML = `<header><h1>Network settings</h1><p>Choose the independent relays that carry your encrypted service messages.</p></header><form data-an-form="settings" class="an-panel"><label class="an-check"><input type="checkbox" name="enabled" ${state.enabled ? "checked" : ""}><span>Enable Agent Network on this desktop</span></label>${field("Relay addresses · one per line", area("endpoints", state.endpoints.join("\n"), 3))}<p class="an-help">Use the same relay addresses on both installations. Leave this empty to test your agents locally. Relays need HTTPS; your KAI account and Composio settings are separate.</p><div class="an-actions"><button class="primary" type="submit">Save settings</button>${btn("Check messages", "refresh")}</div><p class="an-help">${state.pendingMessages} message(s) awaiting relay acceptance. ${esc(state.lastError || "")}</p></form><section class="an-panel"><h2>Private service identity</h2><p class="an-id">${esc(state.address || "Created when you enable the network")}</p><p class="an-help">Separate from your earning wallet. The operator you hire can read your selected input; relays carry encrypted messages. Unregistered cards are verified by signature, not by an on-chain registry.</p></section><section class="an-panel"><h2>KAI service payments</h2><p>Not enabled in this deployment. Free jobs transfer no KAI and do not earn paid-service reputation. Existing compute earnings continue in Earn KAI.</p></section>`; return; }
    if (tab === "discover" || tab === "mine") {
      const mine = tab === "mine", items = mine ? state.agents : [...state.cards, ...state.agents.map(a => a.card)].filter((c, i, all) => all.findIndex(x => x.payload.agent_id === c.payload.agent_id) === i);
      main.innerHTML = `<header class="an-heading"><div><p class="an-eyebrow">${mine ? "YOUR SERVICES" : "KAI AGENT NETWORK"}</p><h1>${mine ? "My agents" : "Find an agent for the job"}</h1><p>${mine ? "Build from a template or a saved workflow. Test before opening your host to callers." : "Explore signed service cards and send only the input you choose."}</p></div><div class="an-actions">${mine ? btn("Create agent", "create", "", "primary") : btn("Refresh directory", "discover", "", "primary")}${btn("Import service card", "import")}</div></header>${!mine ? `<label class="an-search"><span class="sr-only">Search agents</span><input type="search" id="an-search" placeholder="Search by name or capability" value="${esc(search)}"></label>` : ""}<div class="an-grid">${items.map(item => { const a = mine ? item : null, c = mine ? item.card.payload : item.payload; return `<article class="an-card" data-search="${esc((c.name + " " + c.description + " " + c.capabilities.join(" ")).toLowerCase())}"><div class="an-card-top"><span class="an-monogram">${esc(c.name.slice(0, 1).toUpperCase())}</span><span class="an-badge">${mine ? a.accepting ? "Host open" : "Host paused" : "Free service"}</span></div><h2>${esc(c.name)}</h2><p>${esc(c.description)}</p><div class="an-tags">${c.capabilities.map(t => `<span>${esc(t)}</span>`).join("")}</div><p class="an-meta">Version ${esc(c.sequence)} · ${esc(c.agent_id.slice(0, 8))}<br>Selected input only · local model on operator’s host</p><div class="an-actions">${btn(mine ? "Test agent" : "View & request", "hire", c.agent_id, "primary")}${mine ? btn("Edit", "edit", c.agent_id) + btn("More", "details", c.agent_id) : ""}</div></article>`; }).join("")}</div>${!items.length ? empty(mine ? "Your first agent starts here" : "Connect to a directory", mine ? "Turn a useful routine into a reusable service. A connection-check template works without a model." : "Add a relay address in Network settings, import a signed invitation, or create your first local agent.", btn(mine ? "Create agent" : "Network settings", mine ? "create" : "tab", mine ? "" : "settings", "primary")) : ""}`; filter(); return;
    }
    if (tab === "jobs") {
      const selected = state.jobs.find(j => j.id + ":" + j.role === selection);
      main.innerHTML = `<header class="an-heading"><div><h1>Jobs</h1><p>Review quotes, follow execution, and inspect each delivery.</p></div>${btn("Refresh", "refresh")}</header>${selected ? `<section class="an-panel"><div class="an-heading"><div><span class="an-badge">${esc(selected.status.replaceAll("_", " "))}</span><h2>${esc(selected.name)}</h2></div>${btn("Close details", "closeJob")}</div><p class="an-meta">${selected.role === "host" ? "Hosted here" : "Requested by you"} · ${esc(date(selected.at))}</p><h3>Input</h3><pre>${esc(typeof selected.input === "string" ? selected.input : JSON.stringify(selected.input, null, 2))}</pre>${selected.quote ? `<p class="an-help">Quote: ${esc(selected.quote.payload.amount_atoms)} KAI base units · exact service version ${esc(selected.quote.payload.service_version_hash.slice(0, 12))}</p>` : ""}${selected.output != null ? `<h3>Delivery</h3><pre>${esc(typeof selected.output === "string" ? selected.output : JSON.stringify(selected.output, null, 2))}</pre><p class="an-help">Integrity checked · ${esc(selected.resultHash)}</p>` : ""}${selected.error ? `<p class="an-error">${esc(selected.error)}</p>` : ""}${selected.pending ? `<pre>${esc(JSON.stringify(selected.pending, null, 2))}</pre>` : ""}<div class="an-actions">${selected.role === "buyer" && selected.status === "quoted" ? btn("Review & send input", "submit", selected.id, "primary") : ""}${selected.role === "buyer" && selected.status === "delivered" ? btn("Accept result", "accept", selected.id, "primary", "buyer") + btn("Reject result", "reject", selected.id, "", "buyer") + btn("Save result", "download", selected.id) : ""}${selected.role === "host" && selected.status === "interrupted" ? btn("Resume", "resume", selected.id, "", "host") : ""}${selected.role === "host" && selected.status === "waiting" ? btn("Approve step", "approve", selected.id, "", "host") : ""}${!["accepted", "cancelled", "failed", "rejected"].includes(selected.status) ? btn("Cancel job", "cancel", selected.id, "", selected.role) : btn("Remove local receipt", "remove", selected.id, "", selected.role)}</div>${selected.steps.length ? `<ol class="an-steps">${selected.steps.map(s => `<li><span>${esc(s.label)}</span><small>${esc(s.status)}</small></li>`).join("")}</ol>` : ""}</section>` : ""}<div class="an-jobs">${state.jobs.map(j => `<button type="button" class="an-job" data-an="job" data-id="${esc(j.id + ":" + j.role)}"><span><strong>${esc(j.name)}</strong><small>${j.role === "host" ? "Hosted here" : "Requested by you"} · ${esc(date(j.at))}</small></span><span class="an-badge">${esc(j.status.replaceAll("_", " "))}</span><span aria-hidden="true">›</span></button>`).join("")}</div>${!state.jobs.length ? empty("No jobs yet", "Test one of your agents or request a service from Discover.") : ""}`; return;
    }
    if (tab === "earnings") { const accepted = state.jobs.filter(j => j.role === "host" && j.status === "accepted").length; main.innerHTML = `<header><h1>Agent service earnings</h1><p>Service revenue is separate from compute-provider earnings.</p></header><section class="an-panel"><div class="an-metric">0 <small>KAI service revenue</small></div><p>${accepted} accepted free job(s). Free jobs create no paid revenue or paid reputation.</p><p class="an-help">Paid services remain unavailable until the Agent Network registry, escrow, budget vault, and sponsor are deployed and validated on testnet.</p></section>`; return; }
    main.innerHTML = `<header><h1>Activity</h1><p>Your installation’s service activity. Financial chain events will be shown separately when paid services are enabled.</p></header><ol class="an-activity">${state.activity.map(e => `<li><span class="an-dot"></span><div><strong>${esc(e.detail)}</strong><p>${esc(e.type)} · ${esc(date(e.at))}</p></div></li>`).join("")}</ol>${!state.activity.length ? empty("A quiet network, for now", "Agent changes and job outcomes will appear here.") : ""}`;
  }
  function editorHTML() {
    if (editor.kind === "import") return `<header><h1>Import a service card</h1><p>Paste the signed card shared by its owner. KAI verifies its identity and version.</p></header><form data-an-form="import" class="an-panel">${field("Signed service card", area("text", "", 10))}<div class="an-actions"><button class="primary" type="submit">Verify & import</button>${btn("Cancel", "close")}</div></form>`;
    if (editor.kind === "hire") { const c = editor.card.payload; return `<header><h1>${esc(c.name)}</h1><p>${esc(c.description)}</p></header><form data-an-form="hire" class="an-panel"><p><strong>Free service</strong> · up to ${c.limits.seconds} seconds · ${c.limits.steps} steps</p><p class="an-help">Only the selected input is sent after you review the quote. The host processes it using its local model. Your Brain, wallet and connected accounts are not shared.</p>${field(c.input_schema.type === "string" ? "What should this agent work on?" : "Service input (JSON)", area("input", "", 8))}<div class="an-actions"><button class="primary" type="submit">Request quote</button>${btn("Cancel", "close")}</div></form>`; }
    if (editor.kind === "details") { const a = editor.agent; return `<header><h1>${esc(a.card.payload.name)}</h1><p>Control how this service is shared and hosted.</p></header><section class="an-panel"><p>${a.accepting ? "This desktop accepts jobs while KAI is open." : "New remote jobs are paused. Local tests remain available."}</p><div class="an-actions">${btn(a.accepting ? "Pause host" : "Open host to callers", "host", a.id, "primary")}${btn("Publish card", "publish", a.id)}${btn("Export invitation", "export", a.id)}${btn("Retire listing", "retire", a.id)}${btn("Back", "close")}</div><p class="an-help">Publishing shares the name, description, capabilities, endpoints and service identity with your selected directories. The executable workflow and private installation keys stay on this machine.</p></section>`; }
    const a = editor.agent, c = a?.card.payload;
    return `<header><h1>${a ? "Edit agent" : "Create an agent"}</h1><p>A small, useful service powered by a reviewed workflow.</p></header><form data-an-form="save" class="an-panel"><div class="an-form-grid">${field("Name", input("name", c?.name || ""))}${field("Template", `<select name="template">${[["echo", "Connection check · no model"], ["summary", "Summarize supplied text"], ["review", "Review a supplied report"], ["translate", "Translate text"], ["workflow", "Use a saved workflow"]].map(([k, v]) => option(k, v, a ? "workflow" : "echo")).join("")}</select>`)}${field("Local model", `<select name="model">${option("", "Choose when using reasoning", a?.definition.model)}${state.models.map(m => option(m.alias, m.alias, a?.definition.model)).join("")}</select>`)}${field("Saved workflow", `<select name="workflowId">${option("", a ? "Keep current definition" : "Select a reviewed workflow", "")}${workflows.filter(w => !w.draft).map(w => option(w.id, w.name, "")).join("")}</select>`)}</div>${field("What this service does", area("description", c?.description || "", 3))}${field("Capabilities · comma separated", input("capabilities", c?.capabilities.join(", ") || "text"))}<p class="an-help">Service workflows can reason locally, transform data, branch and loop. Personal Brain, connected accounts, desktop actions and scheduled triggers are not allowed in a public service.</p><div class="an-actions"><button class="primary" type="submit">Save agent</button>${btn("Open workflow builder", "builder")}${btn("Cancel", "close")}</div></form>`;
  }
  function filter() { root()?.querySelectorAll(".an-card").forEach(c => { c.hidden = !c.dataset.search.includes(search.toLowerCase()); }); }
  function download(name, text) { const url = URL.createObjectURL(new Blob([text], { type: "text/plain;charset=utf-8" })), a = document.createElement("a"); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  async function action(name, id, role) {
    if (name === "tab") { tab = id; editor = null; selection = null; draw(); return; }
    if (name === "close") { editor = null; draw(); return; }
    if (name === "builder") { if (typeof activateView === "function") activateView("workflows"); return; }
    if (name === "create" || name === "edit") { workflows = (await window.KaiCompanionClient.checked(bridge.manage("status"))).workflows; editor = { kind: "save", agent: state.agents.find(a => a.id === id) }; draw(); return; }
    if (name === "import") { editor = { kind: "import" }; draw(); return; }
    if (name === "details") { editor = { kind: "details", agent: state.agents.find(a => a.id === id) }; draw(); return; }
    if (name === "hire") { editor = { kind: "hire", card: state.cards.find(c => c.payload.agent_id === id) || state.agents.find(a => a.id === id)?.card }; draw(); return; }
    if (name === "job") { selection = id; draw(); return; }
    if (name === "closeJob") { selection = null; draw(); return; }
    if (name === "export") { const card = state.agents.find(a => a.id === id)?.card; const canonical = v => Array.isArray(v) ? "[" + v.map(canonical).join(",") + "]" : v && typeof v === "object" ? "{" + Object.keys(v).sort().map(k => JSON.stringify(k) + ":" + canonical(v[k])).join(",") + "}" : JSON.stringify(v); download("kai-agent-" + id.slice(0, 8) + ".json", canonical(card)); return; }
    if (name === "download") { download("kai-agent-result-" + id.slice(0, 8) + ".txt", (j => typeof j.output === "string" ? j.output : JSON.stringify(j.output, null, 2))(state.jobs.find(j => j.id === id && j.role === "buyer"))); return; }
    if (name === "host") { await call("Accepting", { id, enabled: !state.agents.find(a => a.id === id).accepting }); editor = null; }
    else if (name === "publish") { await call("Publish", { id }); editor = null; }
    else if (name === "retire") { await call("Retire", { id }); editor = null; }
    else if (name === "discover") await call("Discover", { query: search });
    else if (name === "submit") await call("Submit", { id });
    else if (name === "refresh") await call("Refresh");
    else if (["cancel", "accept", "reject", "resume", "approve", "remove"].includes(name)) await call("Job", { id, action: name, role });
    await refresh(); draw();
  }
  root()?.addEventListener("click", async e => { const b = e.target.closest("[data-an]"); if (!b || busy) return; busy = true; b.disabled = true; try { await action(b.dataset.an, b.dataset.id, b.dataset.role); } catch (e) { notice(e.message, true); } finally { busy = false; b.disabled = false; } });
  root()?.addEventListener("input", e => { if (e.target.id === "an-search") { search = e.target.value; filter(); } });
  root()?.addEventListener("submit", async e => {
    const f = e.target.closest("[data-an-form]"); if (!f) return; e.preventDefault(); if (busy) return; busy = true;
    const val = name => f.elements.namedItem(name)?.value || "";
    try {
      if (f.dataset.anForm === "settings") await call("Settings", { enabled: f.elements.enabled.checked, endpoints: val("endpoints").split(/\n/).map(x => x.trim()).filter(Boolean) });
      if (f.dataset.anForm === "import") { await call("Import", { text: val("text").trim() }); editor = null; tab = "discover"; }
      if (f.dataset.anForm === "save") { const a = editor.agent; await call("Save", { ...(a ? { id: a.id } : {}), name: val("name"), description: val("description"), capabilities: val("capabilities").split(",").map(x => x.trim()).filter(Boolean), template: val("template"), model: val("model"), ...(val("template") === "workflow" ? val("workflowId") ? { workflowId: val("workflowId") } : a ? { definition: a.definition } : (() => { throw new Error("Select a saved workflow."); })() : {}) }); editor = null; tab = "mine"; }
      if (f.dataset.anForm === "hire") { let input = val("input"); if (editor.card.payload.input_schema.type !== "string") input = JSON.parse(input); const id = await call("Quote", { id: editor.card.payload.agent_id, input }); selection = id + ":buyer"; editor = null; tab = "jobs"; }
      await refresh(); draw(); notice("Saved.");
    } catch (e) { notice(e.message, true); } finally { busy = false; }
  });
  async function render() { clearTimeout(timer); if (!bridge) { draw(); return; } try { await refresh(); draw(); } catch (e) { root().textContent = e.message; } poll(); }
  function poll() { clearTimeout(timer); timer = setTimeout(async () => { if (root()?.hidden) return; if (!busy && !editor && tab === "jobs") { try { const before = JSON.stringify(state.jobs); await refresh(); if (before !== JSON.stringify(state.jobs) && !root().querySelector("form:focus-within")) draw(); } catch (e) { notice(e.message, true); } } poll(); }, 2000); }
  window.KaiAgentNetwork = { render };
})();
