"use strict";
(() => {
  const bridge = window.kaiCompanionBridge, client = window.KaiCompanionClient;
  const esc = s => String(s ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
  const date = n => n ? new Date(n).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) : "Never";
  const button = (label, action, id = "", cls = "") => `<button type="button" class="${cls}" data-hub-action="${action}" data-id="${esc(id)}">${esc(label)}</button>`;
  const field = (label, input, full = false) => `<label class="hub-field ${full ? "hub-full" : ""}"><span>${label}</span>${input}</label>`;
  const input = (name, value = "", placeholder = "") => `<input name="${name}" value="${esc(value)}" placeholder="${esc(placeholder)}"/>`;
  const area = (name, value = "", rows = 4) => `<textarea name="${name}" rows="${rows}">${esc(value)}</textarea>`;
  const select = (name, values, selected) => `<select name="${name}">${values.map(v => { const [key, label] = Array.isArray(v) ? v : [v, v]; return `<option value="${esc(key)}" ${key === selected ? "selected" : ""}>${esc(label)}</option>`; }).join("")}</select>`;
  const check = (name, label, value) => `<label class="hub-check"><input name="${name}" type="checkbox" ${value ? "checked" : ""}/><span>${label}</span></label>`;
  const empty = (title, detail) => `<div class="hub-empty"><strong>${title}</strong><p>${detail}</p></div>`;
  let state, current = "brain", tab = { brain: "map", workflows: "saved", connections: "apis" }, timer, editor = null, busy = false;
  const host = () => document.getElementById("view-" + current);
  const manage = (action, value) => client.checked(bridge.manage(action, value));
  const value = (form, name) => form.elements.namedItem(name)?.value || "";
  const bool = (form, name) => form.elements.namedItem(name)?.checked === true;
  const json = (form, name, fallback = {}) => { const s = value(form, name).trim(); try { return s ? JSON.parse(s) : fallback; } catch { throw new Error(`Enter valid JSON for ${name}.`); } };
  function note(message, error = false) { const n = host()?.querySelector(".hub-notice"); if (n) { n.textContent = message; n.classList.toggle("error", error); } }
  async function refresh() { state = await manage("status"); }
  function shell() {
    const titles = { brain: ["KAI Brain", "A memory of your world, built from what you choose to share."], workflows: ["Workflows", "Teach KAI a routine. Review the steps, then run it whenever you need."], connections: ["Connections", "Your accounts and APIs, using credentials you manage."] };
    const tabs = { brain: [["map", "Memory map"], ["notes", "Notes"], ["goals", "Goals"], ["sources", "Sources & sync"]], workflows: [["saved", "My workflows"], ["runs", "Run history"]], connections: [["apis", "My APIs"], ["tools", "Models & other tools"]] };
    host().innerHTML = `<header class="hub-header"><div><div class="hub-eyebrow">KAI COMPANION</div><h1>${titles[current][0]}</h1><p>${titles[current][1]}</p></div><span class="hub-badge">On this computer</span></header><div class="hub-notice" role="status" aria-live="polite"></div><nav class="hub-tabs" aria-label="${current} sections">${tabs[current].map(([key, label]) => button(label, "tab", key, key === tab[current] ? "active" : "")).join("")}</nav><div class="hub-content"></div>`;
  }
  function draw() {
    shell(); const out = host().querySelector(".hub-content");
    if (!bridge) { out.innerHTML = empty("Open the installed KAI desktop app", "Brain, private API connections, and durable workflows are available in Koinos AI Test."); return; }
    if (state.locked) { out.innerHTML = empty("Your companion data is locked", "Unlock your original OS keychain and restart KAI. Your saved data will stay intact."); return; }
    if (editor) { out.innerHTML = editorHTML(); return; }
    if (current === "brain") drawBrain(out);
    if (current === "workflows") drawWorkflows(out);
    if (current === "connections") drawConnections(out);
  }
  function drawBrain(out) {
    if (["map", "notes"].includes(tab.brain)) {
      out.innerHTML = `<div class="hub-toolbar"><div class="hub-search"><input id="brain-search" aria-label="Search Brain" placeholder="Search memories, people, projects…"/></div>${button("Add a note", "newNote", "", "primary")}${button("Import file", "import")}${button("Export Brain", "exportBrain")}</div><div class="hub-metrics"><div><b>${state.notes.length}</b><span>Memories</span></div><div><b>${state.goals.filter(g => g.status === "active").length}</b><span>Active goals</span></div><div><b>${state.sources.length}</b><span>Sources</span></div><label class="hub-check"><input id="brain-recall" type="checkbox" ${state.settings.recall ? "checked" : ""}/>Use Brain in replies</label></div><p class="hub-help">Relevant notes and active goals support replies with a local model or your private API model. Imported text is source material. Network worker models do not receive automatic Brain recall.</p><div id="brain-results"></div>`;
      drawNotes("");
    } else if (tab.brain === "goals") {
      out.innerHTML = `<div class="hub-toolbar"><p>Tell KAI what matters and keep its attention on your priorities.</p>${button("Add a goal", "newGoal", "", "primary")}</div><div class="hub-goal-board">${["active", "paused", "done"].map(status => `<section><h3>${{ active: "In focus", paused: "On hold", done: "Completed" }[status]}</h3>${state.goals.filter(g => g.status === status).map(g => `<article class="hub-card"><span class="hub-badge">${g.priority === "high" ? "High priority" : "Goal"}</span><h3>${esc(g.title)}</h3><p>${esc(g.detail)}</p><div class="hub-actions">${button("Edit", "editGoal", g.id)}${status !== "done" ? button("Complete", "completeGoal", g.id) : ""}${button("Delete", "deleteGoal", g.id)}</div></article>`).join("") || `<p class="hub-help">No goals here yet.</p>`}</section>`).join("")}</div>`;
    } else {
      out.innerHTML = `<div class="hub-toolbar">${button("Import text file", "import", "", "primary")}${button("Add API source", "newSource")}${button("Import previous memories", "importLegacy")}</div><p class="hub-help">Choose TXT, Markdown, CSV, or JSON files up to 200 KB. API sources read a saved GET operation; optional sync runs every 20 minutes while KAI is open. Re-importing a file with the same name replaces its indexed content.</p><div class="hub-grid">${state.sources.map(s => `<article class="hub-card"><span class="hub-badge">${s.kind === "file" ? "Imported file" : "API source"}</span><h3>${esc(s.name)}</h3><p>${s.chunks || 0} indexed sections · Last sync ${date(s.lastSync)}</p>${s.error ? `<p class="error">${esc(s.error)}</p>` : ""}<div class="hub-actions">${s.kind === "connection" ? button(state.syncing.includes(s.id) ? "Syncing…" : "Sync now", "sync", s.id) + button(s.autoSync ? "Pause auto-sync" : "Enable auto-sync", "sourceToggle", s.id) : ""}${button("Remove source", "deleteSource", s.id)}</div></article>`).join("") || empty("Give KAI useful context", "Import your project notes or connect a source you want KAI to remember.")}</div><h2 class="hub-section-title">Recent sync activity</h2><div class="hub-history">${state.syncs.slice(0, 15).map(s => `<div><strong>${esc(s.name)}</strong><span>${esc(s.status)}${s.added ? " · " + s.added + " sections" : ""}</span><time>${date(s.at)}</time></div>`).join("") || `<p class="hub-help">Sync activity will appear here.</p>`}</div>`;
    }
  }
  function drawNotes(query) {
    const results = document.getElementById("brain-results"); if (!results) return;
    const items = state.notes.filter(n => (n.title + " " + n.text + " " + n.tags.join(" ")).toLowerCase().includes(query.toLowerCase()));
    const card = n => `<article class="hub-card hub-note"><div class="hub-card-top"><span class="hub-badge">${esc(n.category)}${n.pinned ? " · Pinned" : ""}</span><small>${esc(n.source || "You")}</small></div><h3>${esc(n.title)}</h3><p class="hub-note-excerpt">${esc(n.text.slice(0, 280))}${n.text.length > 280 ? "…" : ""}</p><div class="hub-tags">${n.tags.map(t => `<span>${esc(t)}</span>`).join("")}</div><div class="hub-actions">${button(n.sourceId ? "Read" : "Edit", "editNote", n.id)}${!n.sourceId ? button("Delete", "deleteNote", n.id) : ""}</div></article>`;
    if (!items.length) { results.innerHTML = empty(query ? "No matching memories" : "Start with something KAI should know", query ? "Try a project name, person, or phrase." : "Add a preference, introduce a person, or import your project notes. You can edit or remove them at any time."); return; }
    if (tab.brain === "map" && !query) {
      results.innerHTML = `<div class="hub-tree"><div class="hub-tree-root"><span class="hub-orb"></span><div><b>Your world</b><small>Organized by category and source</small></div></div>${["preferences", "people", "projects", "notes", "sources"].filter(c => items.some(n => n.category === c)).map(c => `<details class="hub-tree-branch" open><summary>${esc(c[0].toUpperCase() + c.slice(1))}<span>${items.filter(n => n.category === c).length}</span></summary><div class="hub-grid">${items.filter(n => n.category === c).slice(0, 30).map(card).join("")}</div></details>`).join("")}</div>`;
    } else results.innerHTML = `<div class="hub-grid">${items.slice(0, 100).map(card).join("")}</div>${items.length > 100 ? "<p>Showing the first 100 results. Narrow your search.</p>" : ""}`;
  }
  function drawWorkflows(out) {
    if (tab.workflows === "runs") {
      out.innerHTML = `<p class="hub-help">Runs keep a checkpoint after each completed step. A paused run waits for you. After an interrupted external action, inspect the destination before starting another run.</p><div class="hub-run-list">${state.runs.map(r => `<details class="hub-card hub-run" ${["waiting", "running", "interrupted"].includes(r.status) ? "open" : ""}><summary><span><b>${esc(r.name)}</b><small>${date(r.startedAt)} · ${esc(r.trigger)}</small></span><span class="hub-badge ${r.status}">${esc(r.status)}</span></summary><div class="hub-run-body">${r.steps.map((s, i) => `<details><summary>${i + 1}. ${esc(s.label)} · ${esc(s.status)}</summary><pre>${esc(s.output)}</pre></details>`).join("")}${r.pending ? `<div class="hub-pending"><b>Waiting for approval · Step ${r.index + 1}</b><pre>${esc(JSON.stringify(r.pending, null, 2))}</pre></div>` : ""}${r.error ? `<p class="error">${esc(r.error)}</p>` : ""}<div class="hub-actions">${["waiting", "interrupted"].includes(r.status) && !r.inFlight ? button("Review & resume", "resume", r.id, "primary") : ""}${["running", "waiting", "interrupted"].includes(r.status) ? button("Cancel run", "cancelRun", r.id) : ""}</div></div></details>`).join("") || empty("Your first run starts here", "Run a saved workflow to see its progress and results.")}</div>`;
      return;
    }
    out.innerHTML = `<div class="hub-toolbar">${button("New workflow", "newWorkflow", "", "primary")}${button("Import workflow", "importWorkflow")}${button("Scheduled prompts", "legacyTasks")}</div><p class="hub-help">Schedules run while the desktop app is open. Reasoning steps use an installed local model. API actions use your saved connections; writes pause for approval.</p><div class="hub-grid">${state.workflows.map(w => `<article class="hub-card"><div class="hub-card-top"><span class="hub-badge">${w.draft ? "Draft · review required" : w.enabled ? w.schedule.kind === "manual" ? "Manual" : "Schedule on" : "Schedule off"}</span><small>${w.steps.length} steps</small></div><h3>${esc(w.name)}</h3><p>${esc(w.description || w.steps.map(s => s.label).join(" → "))}</p>${w.nextRunAt ? `<small>Next run ${date(w.nextRunAt)}</small>` : ""}<div class="hub-mini-flow">${w.steps.slice(0, 5).map((s, i) => `<span>${i + 1}. ${esc(s.label)}</span>`).join("")}</div><div class="hub-actions">${!w.draft ? button("Run", "run", w.id, "primary") : ""}${button("Edit", "editWorkflow", w.id)}${button("Export", "exportWorkflow", w.id)}${button("Delete", "deleteWorkflow", w.id)}</div></article>`).join("") || empty("Make room for the work you enjoy", "Start with a template below or describe the routine you want KAI to help with.")}</div><h2 class="hub-section-title">Start from a template</h2><div class="hub-grid">${[["briefing", "Project briefing", "Search your Brain, summarize the latest context, and save a readable result."], ["review", "Weekly goal review", "Review project notes, draft next steps, and pause before remembering them."], ["api", "API digest", "Read a connection, summarize the response, and keep the result in run history."]].map(([key, title, detail]) => `<button class="hub-template" data-hub-action="templateWorkflow" data-id="${key}"><strong>${title}<span>↗</span></strong><p>${detail}</p></button>`).join("")}</div>`;
  }
  function drawConnections(out) {
    if (tab.connections === "tools") {
      out.innerHTML = `<div class="hub-grid"><article class="hub-card"><h3>AI models</h3><p>Use your own OpenAI or Anthropic key in private desktop chat, or install a local model for private, scheduled work.</p>${button("Provider settings", "providerSettings")}${button("Local model library", "modelLibrary")}</article><article class="hub-card"><h3>MCP, email & calendars</h3><p>KAI's existing tool servers, email accounts, and calendar connections are available in Tools with their current permissions.</p>${button("Open Tools", "legacyTools")}</article></div>`;
      return;
    }
    out.innerHTML = `<div class="hub-toolbar"><p>Tokens are encrypted with your OS credentials and stay out of the model.</p>${button("Add connection", "newConnection", "", "primary")}</div><div class="hub-grid">${state.connections.map(c => `<article class="hub-card"><div class="hub-card-top"><span class="hub-badge">${c.enabled ? esc(c.status) : "Disabled"}</span><small>${c.operations.length} operations</small></div><h3>${esc(c.name)}</h3><p class="hub-url">${esc(c.baseUrl)}</p><p>${c.allowAgent ? "Available to KAI with approval" : "Manual use only"}<br/>${c.allowSync ? "Background reads allowed" : "Background reads off"}</p><div class="hub-actions">${button("Open & test", "useConnection", c.id, "primary")}${button("Edit", "editConnection", c.id)}${button("Remove", "deleteConnection", c.id)}</div></article>`).join("") || empty("Connect the services you use", "Choose a starting template, paste your own token, and test a request. You control which operations KAI can use.")}</div><h2 class="hub-section-title">Connect with your own API</h2><div class="hub-catalog">${state.templates.map(t => button(t.name, "connectionTemplate", t.id)).join("")}</div><p class="hub-help">GitHub, Notion, Slack, and Home Assistant include starter operations. Custom APIs accept HTTPS endpoints, bearer tokens or a named API-key header. Tokens and permissions are managed in your service account.</p>`;
  }
  function editorHTML() {
    const { kind, item } = editor;
    const top = `<div class="hub-toolbar">${button("← Back", "closeEditor")}<h2>${esc({ note: item.sourceId ? "Source content" : "Memory", goal: "Goal", workflow: "Workflow builder", connection: "API connection", request: "Use connection", source: "Add a Brain source", run: "Start workflow" }[kind])}</h2></div>`;
    if (kind === "run") return top + `<form data-hub-form="run" class="hub-panel"><h3>${esc(item.name)}</h3>${field("Run input (optional)", area("input", "", 4), true)}<p class="hub-help">Use a project name or topic to fill {{input}} in the saved steps.</p><button class="primary">Start run</button></form>`;
    if (kind === "note") return top + `<form data-hub-form="note" class="hub-panel"><div class="hub-form-grid">${field("Title", input("title", item.title), true)}${field("Category", select("category", ["notes", "preferences", "people", "projects"], item.category))}${field("Tags", input("tags", (item.tags || []).join(", "), "Comma-separated"))}${field("What should KAI know?", area("text", item.text, 9), true)}</div>${item.sourceId ? `<p>Imported from ${esc(item.source)}. Re-import or sync its source to update.</p>` : `${check("pinned", "Keep this note prominent in recall", item.pinned)}<button class="primary">Save memory</button>`}</form>`;
    if (kind === "goal") return top + `<form data-hub-form="goal" class="hub-panel"><div class="hub-form-grid">${field("Goal", input("title", item.title), true)}${field("Why it matters / next steps", area("detail", item.detail), true)}${field("Status", select("status", ["active", "paused", "done"], item.status))}${field("Priority", select("priority", ["normal", "high"], item.priority))}</div><button class="primary">Save goal</button></form>`;
    if (kind === "connection") return top + `<form data-hub-form="connection" class="hub-panel"><div class="hub-form-grid">${field("Name", input("name", item.name))}${field("API base URL", input("baseUrl", item.baseUrl))}${field("Authentication", select("auth", [["bearer", "Bearer token"], ["header", "API-key header"], ["none", "No authentication"]], item.auth))}${field("Secret header (header auth only)", input("headerName", item.headerName || "X-API-Key"))}${field("Your API token", '<input type="password" name="secret" autocomplete="off" placeholder="' + (item.id ? "Saved securely · leave blank to keep" : "Paste your token") + '"/>', true)}</div><div class="hub-checks">${check("enabled", "Enable connection", item.enabled !== false)}${check("allowAgent", "Let KAI use these operations (each call asks for approval)", item.allowAgent)}${check("allowSync", "Allow saved sources and workflows to make background GET requests", item.allowSync)}</div><details class="hub-advanced" open><summary>API operations and version headers</summary><p class="hub-help">Each operation has a unique id, name, HTTP method, and path. Use {owner}, {repo}, or other placeholders for request variables. Write methods always require review.</p>${field("Operations (JSON)", area("operations", JSON.stringify(item.operations, null, 2), 12), true)}${field("Version headers (JSON)", area("headers", JSON.stringify(item.headers || {}, null, 2), 3), true)}</details><button class="primary">Save connection</button></form>`;
    if (kind === "request") return top + `<form data-hub-form="request" class="hub-panel"><h3>${esc(item.name)}</h3><p>${esc(item.baseUrl)}</p><div class="hub-form-grid">${field("Operation", select("operationId", item.operations.map(o => [o.id, o.name + " · " + o.method]), item.operations[0].id), true)}${field("Path variables (JSON)", area("variables", "{}", 5))}${field("Request body (writes only, JSON)", area("body", "{}", 5))}</div><p class="hub-help" id="operation-help">${esc(item.operations[0].path)}</p><button class="primary">Run request</button><pre id="connection-result" class="hub-result" aria-live="polite"></pre></form>`;
    if (kind === "source") return top + `<form data-hub-form="source" class="hub-panel"><div class="hub-form-grid">${field("Source name", input("name", "", "KAI project issues"), true)}${field("Connection", select("connectionId", state.connections.filter(c => c.enabled && c.allowSync).map(c => [c.id, c.name]), item.connectionId))}${field("GET operation", select("operationId", sourceOps(item.connectionId), item.operationId))}${field("Path variables (JSON)", area("variables", "{}"), true)}</div>${check("autoSync", "Sync every 20 minutes while KAI is open", false)}<p class="hub-help">Only connections with background reads enabled are listed.</p><button class="primary">Add source</button></form>`;
    return top + `<form data-hub-form="workflow" class="hub-panel"><div class="hub-form-grid">${field("Workflow name", input("name", item.name), true)}${field("Purpose", input("description", item.description), true)}${field("Local reasoning model", select("model", [["", "Choose installed model"], ...state.models.map(m => [m.alias, m.label || m.alias])], item.model))}${field("Run schedule", select("schedule", ["manual", "hourly", "every6h", "daily", "weekly"], item.schedule?.kind || "manual"))}${field("Hour (daily / weekly, local time)", '<input type="number" min="0" max="23" name="hour" value="' + (item.schedule?.hour ?? 9) + '"/>')}${field("Day (weekly)", select("day", [["0", "Sunday"], ["1", "Monday"], ["2", "Tuesday"], ["3", "Wednesday"], ["4", "Thursday"], ["5", "Friday"], ["6", "Saturday"]], String(item.schedule?.day ?? 1)))}</div>${check("enabled", "Enable the saved schedule", item.enabled)}<details class="hub-advanced"><summary>Describe a workflow to KAI</summary>${field("What should the routine do?", area("describe", "", 3), true)}${button("Draft steps with KAI", "draftWorkflow")}<p class="hub-help">Uses the selected local model. Review the generated steps below before saving.</p></details><p class="hub-help">Steps run top to bottom. {{input}} is the run input; {{previous}} is the last step's output. A condition continues only when the previous output contains its text.</p><div class="hub-flow-editor">${item.steps.map(stepHTML).join("")}</div><div class="hub-toolbar">${button("Add step", "addStep")}<button class="primary">Save workflow</button></div></form>`;
  }
  function sourceOps(key) { const c = state.connections.find(c => c.id === key) || state.connections.find(c => c.enabled && c.allowSync); return (c?.operations || []).filter(o => o.method === "GET").map(o => [o.id, o.name]); }
  function stepHTML(s, i) {
    return `<div class="hub-step" data-step="${i}"><div class="hub-step-number">${i + 1}</div><div class="hub-step-main"><div class="hub-form-grid">${field("Step type", select("type", [["brain_search", "Search Brain"], ["prompt", "Ask local model"], ["connection", "Call a connection"], ["condition", "Continue if text matches"], ["approval", "Wait for approval"], ["remember", "Save to Brain"], ["output", "Result"]], s.type))}${field("Label", input("label", s.label))}${field(s.type === "condition" ? "Text to match" : "Instructions or text", area("text", s.text, 3), true)}</div>${s.type === "connection" ? `<div class="hub-form-grid">${field("Connection", select("connectionId", [["", "Choose connection"], ...state.connections.map(c => [c.id, c.name])], s.connectionId))}${field("Operation ID", input("operationId", s.operationId))}${field("Variables (JSON)", area("variables", JSON.stringify(s.variables || {}, null, 2), 4))}${field("Body (JSON)", area("body", JSON.stringify(s.body || {}, null, 2), 4))}</div>` : ""}<div class="hub-actions">${button("Move up", "stepUp", String(i))}${button("Move down", "stepDown", String(i))}${button("Remove step", "removeStep", String(i))}</div></div></div>`;
  }
  function collectWorkflow() {
    const f = host().querySelector("form");
    return { ...editor.item, name: value(f, "name"), description: value(f, "description"), model: value(f, "model"), enabled: bool(f, "enabled"), schedule: { kind: value(f, "schedule"), hour: Number(value(f, "hour")), day: Number(value(f, "day")) },
      steps: [...f.querySelectorAll("[data-step]")].map(el => { const v = name => el.querySelector(`[name="${name}"]`)?.value || ""; const s = { type: v("type"), label: v("label"), text: v("text") }; if (s.type === "connection") { s.connectionId = v("connectionId"); s.operationId = v("operationId"); try { s.variables = JSON.parse(v("variables") || "{}"); s.body = JSON.parse(v("body") || "{}"); } catch { throw new Error("Connection step variables and body must be valid JSON."); } } return s; }) };
  }
  function template(key) {
    const search = { type: "brain_search", label: "Gather context", text: "{{input}}" }, ask = { type: "prompt", label: "Write a briefing", text: "Summarize these notes and identify useful next steps. Cite note titles.\n\n{{previous}}" }, result = { type: "output", label: "Keep the result", text: "{{previous}}" };
    return { name: { briefing: "Project briefing", review: "Weekly goal review", api: "API digest" }[key] || "New workflow", model: state.models[0]?.alias || "", schedule: { kind: "manual", hour: 9, day: 1 }, enabled: false, steps: key === "review" ? [search, ask, { type: "remember", label: "Reviewed next steps", text: "{{previous}}" }] : key === "api" ? [{ type: "connection", label: "Read a saved API", connectionId: state.connections[0]?.id || "", operationId: state.connections[0]?.operations[0]?.id || "", variables: {}, body: {} }, ask, result] : [search, ask, result] };
  }
  async function render(view = current) {
    clearTimeout(timer); if (view !== current) editor = null; current = view;
    try { if (bridge) await refresh(); draw(); } catch (e) { shell(); note(e.message, true); }
    poll();
  }
  function poll() {
    clearTimeout(timer); if (!bridge || editor || host()?.hidden) return;
    timer = setTimeout(async () => { if (host()?.hidden || editor || busy) return poll(); try { await refresh(); if (current === "workflows" && tab.workflows === "runs") draw(); } catch { /* show next explicit operation error */ } poll(); }, 2500);
  }
  async function action(name, key) {
    if (name === "tab") { editor = null; tab[current] = key; draw(); poll(); return; }
    if (name === "closeEditor") { editor = null; draw(); poll(); return; }
    if (name === "legacyTools" || name === "providerSettings" || name === "modelLibrary" || name === "legacyTasks") { activateView({ legacyTools: "tools", providerSettings: "settings", modelLibrary: "models", legacyTasks: "tasks" }[name]); return; }
    const editing = { run: ["run", state.workflows.find(w => w.id === key)], newNote: ["note", {}], editNote: ["note", state.notes.find(n => n.id === key)], newGoal: ["goal", {}], editGoal: ["goal", state.goals.find(n => n.id === key)], newWorkflow: ["workflow", template("briefing")], templateWorkflow: ["workflow", template(key)], editWorkflow: ["workflow", state.workflows.find(w => w.id === key)], newConnection: ["connection", state.templates.at(-1)], connectionTemplate: ["connection", state.templates.find(t => t.id === key)], editConnection: ["connection", state.connections.find(c => c.id === key)], useConnection: ["request", state.connections.find(c => c.id === key)], newSource: ["source", { connectionId: state.connections.find(c => c.enabled && c.allowSync)?.id }] };
    if (editing[name]) { const [kind, item] = editing[name]; editor = { kind, item: JSON.parse(JSON.stringify(item || {})) }; if (["newConnection", "connectionTemplate"].includes(name)) delete editor.item.id; draw(); return; }
    if (["addStep", "removeStep", "stepUp", "stepDown"].includes(name)) { editor.item = collectWorkflow(); const i = Number(key), steps = editor.item.steps; if (name === "addStep") steps.push({ type: "prompt", label: "New step", text: "{{previous}}" }); if (name === "removeStep") steps.splice(i, 1); const to = name === "stepUp" ? i - 1 : name === "stepDown" ? i + 1 : -1; if (to >= 0 && to < steps.length) [steps[to], steps[i]] = [steps[i], steps[to]]; draw(); return; }
    if (name === "draftWorkflow") {
      const form = host().querySelector("form"), request = value(form, "describe").trim(); if (!request) throw new Error("Describe the routine first.");
      editor.item = collectWorkflow(); if (!editor.item.model) throw new Error("Choose an installed local model first."); note("KAI is drafting the steps…");
      const response = await KaiProviders.chatFetch("/core/chat/completions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ model: editor.item.model, stream: false, max_tokens: 1500, messages: [{ role: "system", content: 'Draft a KAI workflow. Return ONLY JSON {"steps":[{"type":"brain_search|prompt|approval|remember|output","label":"short label","text":"instructions"}]}. At most 8 steps. Use {{input}} for run input and {{previous}} for last output. No tools, code, or API calls. Add approval before remembering. Do not claim it has run.' }, { role: "user", content: request.slice(0, 4000) }] }) });
      if (!response.ok) throw new Error("The local model could not draft the workflow."); const reply = await response.json(); const raw = reply.choices?.[0]?.message?.content || ""; const parsed = JSON.parse(raw.replace(/^\s*```(?:json)?\s*/, "").replace(/\s*```\s*$/, ""));
      if (!Array.isArray(parsed.steps) || !parsed.steps.length || parsed.steps.length > 8 || parsed.steps.some(s => !["brain_search", "prompt", "approval", "remember", "output"].includes(s.type))) throw new Error("The model did not return a valid draft. Try a clearer description or add steps manually.");
      editor.item.steps = parsed.steps; draw(); note("Draft ready. Review every step and save when it matches your intent."); return;
    }
    const deleting = { deleteNote: ["notes", "note"], deleteGoal: ["goals", "goal"], deleteSource: ["sources", "source and its indexed content"], deleteConnection: ["", "connection"], deleteWorkflow: ["", "workflow and run history"] };
    if (deleting[name]) { if (!confirm("Remove this " + deleting[name][1] + "?")) return; await manage(name === "deleteConnection" ? "removeConnection" : name === "deleteWorkflow" ? "removeWorkflow" : "remove", { id: key, kind: deleting[name][0] }); }
    else if (name === "completeGoal") await manage("goal", { ...state.goals.find(g => g.id === key), status: "done" });
    else if (name === "sourceToggle") await manage("sourceToggle", { id: key, enabled: !state.sources.find(s => s.id === key).autoSync });
    else await manage(name, { id: key });
    await refresh(); draw(); note(name === "sync" ? "Source synced." : name === "run" ? "Workflow started." : "Done."); poll();
  }
  document.addEventListener("click", async e => {
    const b = e.target.closest("[data-hub-action]"); if (!b || !b.closest(".companion-hub") || busy) return;
    busy = true; b.disabled = true;
    try { await action(b.dataset.hubAction, b.dataset.id); } catch (error) { note(error.message, true); }
    finally { busy = false; b.disabled = false; }
  });
  document.addEventListener("input", e => { if (e.target.id === "brain-search") drawNotes(e.target.value); });
  document.addEventListener("change", async e => {
    if (!e.target.closest(".companion-hub")) return;
    try {
      if (e.target.id === "brain-recall") { await manage("recall", { enabled: e.target.checked }); note(e.target.checked ? "Brain recall enabled." : "Automatic Brain recall paused."); }
      if (editor?.kind === "workflow" && e.target.name === "type") { editor.item = collectWorkflow(); draw(); }
      if (editor?.kind === "source" && e.target.name === "connectionId") { const s = host().querySelector('[name="operationId"]'); s.innerHTML = sourceOps(e.target.value).map(([key, label]) => `<option value="${esc(key)}">${esc(label)}</option>`).join(""); }
      if (editor?.kind === "request" && e.target.name === "operationId") document.getElementById("operation-help").textContent = editor.item.operations.find(o => o.id === e.target.value)?.path || "";
    } catch (error) { note(error.message, true); }
  });
  document.addEventListener("submit", async e => {
    const form = e.target.closest("[data-hub-form]"); if (!form) return; e.preventDefault(); if (busy) return; busy = true;
    const submit = form.querySelector('button:not([type="button"])'); if (submit) submit.disabled = true;
    try {
      const kind = form.dataset.hubForm, old = editor.item;
      let body;
      if (kind === "run") body = { id: old.id, input: value(form, "input") };
      if (kind === "note") body = { id: old.id, title: value(form, "title"), text: value(form, "text"), category: value(form, "category"), tags: value(form, "tags"), pinned: bool(form, "pinned") };
      if (kind === "goal") body = { id: old.id, title: value(form, "title"), detail: value(form, "detail"), status: value(form, "status"), priority: value(form, "priority") };
      if (kind === "workflow") body = collectWorkflow();
      if (kind === "connection") { body = { id: old.id, name: value(form, "name"), baseUrl: value(form, "baseUrl"), auth: value(form, "auth"), headerName: value(form, "headerName"), secret: value(form, "secret"), headers: json(form, "headers"), operations: json(form, "operations", []), enabled: bool(form, "enabled"), allowAgent: bool(form, "allowAgent"), allowSync: bool(form, "allowSync") }; form.elements.secret.value = ""; }
      if (kind === "source") body = { name: value(form, "name"), connectionId: value(form, "connectionId"), operationId: value(form, "operationId"), variables: json(form, "variables"), autoSync: bool(form, "autoSync") };
      if (kind === "request") body = { connectionId: old.id, operationId: value(form, "operationId"), variables: json(form, "variables"), body: json(form, "body") };
      note(kind === "request" ? "Running the request…" : "Saving…");
      const result = await manage(kind, body); if (body?.secret) body.secret = "";
      if (kind === "request") { document.getElementById("connection-result").textContent = String(result); note("Request completed."); }
      else { editor = null; if (kind === "run") tab.workflows = "runs"; await refresh(); draw(); note(kind === "run" ? "Workflow started." : "Saved."); poll(); }
    } catch (error) { note(error.message, true); }
    finally { busy = false; if (submit) submit.disabled = false; }
  });
  window.KaiCompanionHub = { render };
})();
