"use strict";
(() => {
  const M = window.KaiWorkflowModel, esc = s => String(s ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
  const date = n => n ? new Date(n).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) : "Never";
  const btn = (label, action, id = "", cls = "") => `<button type="button" class="${cls}" data-wf="${action}" data-id="${esc(id)}">${esc(label)}</button>`;
  const select = (path, label, values, value) => `<label class="wf-field"><span>${label}</span><select data-field="${path}">${values.map(v => { const [key, text] = Array.isArray(v) ? v : [v, v]; return `<option value="${esc(key)}" ${String(key) === String(value) ? "selected" : ""}>${esc(text)}</option>`; }).join("")}</select></label>`;
  const field = (path, label, value = "", kind = "text", hint = "") => `<label class="wf-field"><span>${label}</span>${["area", "json", "code"].includes(kind) ? `<textarea rows="${kind === "code" ? 9 : 4}" data-field="${path}" data-format="${kind}" spellcheck="${kind === "area"}">${esc(kind === "json" ? JSON.stringify(value, null, 2) : value)}</textarea>` : `<input type="${kind === "number" ? "number" : "text"}" data-field="${path}" data-format="${kind}" value="${esc(value)}"/>`}${hint ? `<small>${hint}</small>` : ""}</label>`;
  const check = (path, label, value) => `<label class="wf-check"><input type="checkbox" data-field="${path}" data-format="bool" ${value ? "checked" : ""}/><span>${label}</span></label>`;
  const empty = (title, detail) => `<div class="hub-empty"><strong>${title}</strong><p>${detail}</p></div>`;
  let host, api, data, section, draft = null, savedJSON = "", selected = "", inspector = "node", undo = [], redo = [], zoom = .85, pan = { x: 25, y: 10 }, linking = null, filter = "", runFilter = "", runStatus = "", runId = "", modal = null, proposal = null, busy = false, timer, invalid = "", copied = null;
  const eventChoices = {};
  const clone = M.clone, currentNode = () => draft?.graph.nodes.find(n => n.id === selected), dirty = () => draft && JSON.stringify(draft) !== savedJSON;
  function notice(text, error = false) { const el = host?.querySelector(".wf-notice"); if (el) { el.textContent = text; el.classList.toggle("error", error); } }
  async function refresh() { data = await api.manage("status"); }
  function history() { undo.push(clone(draft)); if (undo.length > 50) undo.shift(); redo = []; }
  function commit(fn) { history(); fn(); invalid = ""; draw(); }
  function open(item) { draft = M.fromLegacy(item); savedJSON = JSON.stringify(draft); selected = draft.graph.nodes[0]?.id || ""; undo = []; redo = []; proposal = null; inspector = "node"; zoom = .85; pan = { x: 25, y: 10 }; runId = ""; draw(); }
  function newFlow() { const trigger = M.node("trigger", "start", { x: 80, y: 70 }); open({ name: "New workflow", description: "", model: data.models[0]?.alias || "", enabled: false, graph: { version: 2, nodes: [trigger], edges: [] } }); }
  function render(out, options) { clearTimeout(timer); host = out; api = options; data = options.state; section = options.section; draw(); poll(); }
  function draw() {
    if (!host) return;
    host.innerHTML = `<div class="wf-workspace ${draft ? "wf-builder" : ""}"><div class="wf-notice" role="status" aria-live="polite"></div>${draft ? builder() : section === "runs" ? runs() : section === "discover" ? discoveries() : section === "templates" ? templateCards() : saved()}${modal ? modalHTML() : ""}</div>`;
    host.onclick = click; host.onchange = change; host.oninput = input; host.onsubmit = submit; host.onkeydown = keydown; host.onpointerdown = pointerdown;
    const viewport = host.querySelector(".wf-viewport"); if (viewport) viewport.addEventListener("wheel", wheel, { passive: false });
    if (draft) paint();
  }
  function saved() {
    const workflows = data.workflows.filter(w => (w.name + " " + w.description).toLowerCase().includes(filter.toLowerCase()));
    return `<div class="wf-heading"><div><h2>Your routines, connected</h2><p>Build a flow once. Run it when you need it, on a schedule, or when something changes.</p></div><div class="hub-actions">${btn("Import", "import")}${btn("New workflow", "new", "", "primary")}</div></div><div class="wf-prompt-bar"><span class="wf-spark">✦</span><input id="wf-quick-prompt" placeholder="Describe a routine you'd like KAI to build…" aria-label="Describe a workflow"/>${btn("Build with KAI", "quickBuild")}</div><div class="wf-list-tools"><input id="wf-filter" aria-label="Search workflows" placeholder="Search workflows" value="${esc(filter)}"/><span>${data.workflows.length} saved · ${data.workflows.filter(w => w.enabled).length} enabled</span></div><div class="wf-saved-list">${workflows.map(w => { const last = data.runs.find(r => r.workflowId === w.id), graph = M.fromLegacy(w).graph, t = graph.nodes.find(n => n.type === "trigger")?.config; return `<article class="wf-saved"><div class="wf-flow-icon">⑂</div><div class="wf-saved-info"><button data-wf="edit" data-id="${esc(w.id)}" class="wf-name">${esc(w.name)}</button><p>${esc(w.description || graph.nodes.filter(n => n.type !== "trigger").map(n => n.label).slice(0, 4).join(" → "))}</p><div class="wf-meta"><span>${graph.nodes.length} nodes</span><span>${esc(w.draft ? "Draft · review needed" : triggerLabel(t))}</span>${last ? `<span class="hub-badge ${esc(last.status)}">${esc(last.status)}</span><span>${date(last.startedAt)}</span>` : `<span>Never run</span>`}</div>${w.nextRunAt ? `<small>Next run ${date(w.nextRunAt)}</small>` : ""}${w.watch?.error ? `<p class="error">${esc(w.watch.error)}</p>` : ""}${w.legacyTask ? `<small>Moved from Tasks${w.legacyTask.needsModel ? " · choose a local model" : ""}${w.legacyTask.lastChatId ? " · previous answers remain in Chat" : ""}</small>` : ""}</div><div class="wf-row-actions"><button data-wf="toggle" data-id="${esc(w.id)}" class="wf-toggle ${w.enabled ? "on" : ""}" role="switch" aria-checked="${!!w.enabled}" aria-label="Enable ${esc(w.name)}" ${w.draft ? "disabled" : ""}><span></span></button>${!w.draft ? btn("Run", "run", w.id, "primary") : ""}<details class="wf-menu"><summary aria-label="More actions for ${esc(w.name)}">•••</summary><div>${btn("Open builder", "edit", w.id)}${btn("Duplicate", "duplicate", w.id)}${btn("Run history", "history", w.id)}${btn("Export", "export", w.id)}${btn("Delete", "delete", w.id)}</div></details></div></article>`; }).join("") || empty("Make room for the work you enjoy", "Start from a template or build your own flow.")}</div><div class="wf-section-heading"><h3>Start from a template</h3>${btn("View all templates", "templates")}</div>${templateCards(true)}`;
  }
  function triggerLabel(c = {}) { return { manual: "On demand", schedule: "Scheduled", source_change: "Source changes", app_change: "App changes", app_event: "App events" }[c.kind] || "On demand"; }
  function templateCards(compact = false) { return `${compact ? "" : `<div class="wf-heading"><div><h2>A useful place to start</h2><p>Every template opens in the builder so you can choose models, apps, and the steps you want.</p></div></div>`}<div class="wf-templates">${M.templates.slice(0, compact ? 4 : undefined).map(([key, name, detail]) => `<button type="button" class="wf-template" data-wf="template" data-id="${key}"><span class="wf-template-icon">${key === "loop" ? "↻" : key === "event" ? "⚡" : "⑂"}</span><strong>${name}</strong><p>${detail}</p><small>Use template →</small></button>`).join("")}</div>`; }
  function runs() {
    const list = data.runs.filter(r => (!runFilter || r.workflowId === runFilter) && (!runStatus || r.status === runStatus));
    return `<div class="wf-heading"><div><h2>Every run, step by step</h2><p>Inspect inputs, results, timings, and decisions. Paused runs wait here for you.</p></div>${btn("Refresh", "refresh")}</div><div class="wf-run-filters">${select("runWorkflow", "Workflow", [["", "All workflows"], ...data.workflows.map(w => [w.id, w.name])], runFilter)}${select("runStatus", "Status", [["", "All statuses"], "running", "waiting", "completed", "failed", "interrupted", "cancelled"], runStatus)}</div><div class="hub-run-list">${list.map(runCard).join("") || empty("No runs here yet", "Run a saved workflow to see its progress and results.")}</div>`;
  }
  function runCard(r) { return `<details class="hub-card hub-run wf-run" data-run="${esc(r.id)}" ${["waiting", "running", "interrupted"].includes(r.status) ? "open" : ""}><summary><span><b>${esc(r.name)}</b><small>${date(r.startedAt)} · ${esc(r.trigger)}${r.dryRun ? " · simulated preview" : ""}</small></span><span class="hub-badge ${esc(r.status)}">${esc(r.status)}</span></summary><div class="hub-run-body"><div class="hub-actions">${r.spec.graph ? btn("View on canvas", "runCanvas", r.id) : ""}${["waiting", "interrupted"].includes(r.status) && !r.inFlight ? btn("Review & resume", "resume", r.id, "primary") : ""}${r.status === "waiting" ? btn("Reject", "reject", r.id) : ""}${["running", "waiting", "interrupted"].includes(r.status) ? btn("Cancel run", "cancel", r.id) : btn("Run again", "run", r.workflowId)}</div>${r.pending ? `<div class="hub-pending"><b>Waiting for your decision</b><pre>${esc(JSON.stringify(r.pending, null, 2))}</pre></div>` : ""}${r.error ? `<p class="error">${esc(r.error)}</p>` : ""}${r.steps.map((s, i) => `<details class="wf-run-step"><summary><span class="wf-step-status ${esc(s.status)}">${s.status === "completed" ? "✓" : s.status === "running" ? "◌" : "!"}</span>${i + 1}. ${esc(s.label)}<small>${esc(s.status)}${s.durationMs != null ? " · " + (s.durationMs / 1000).toFixed(1) + "s" : ""}${s.attempts > 1 ? " · " + s.attempts + " attempts" : ""}</small></summary>${s.frameId && s.frameId !== "root" ? `<p class="hub-help">${esc(s.frameId)}</p>` : ""}${s.input ? `<b>Input</b><pre>${esc(JSON.stringify(s.input, null, 2))}</pre>` : ""}<b>Output</b><pre>${esc(s.error || s.output || "Running…")}</pre></details>`).join("")}</div></details>`; }
  function discoveries() { const suggestions = data.workflowState?.suggestions || [], settings = data.workflowState?.discovery || {}; return `<div class="wf-heading"><div><h2>Discover useful routines</h2><p>KAI can suggest workflows from your goals, personal notes, and connected apps. You choose what to build.</p></div></div><form class="wf-discover-form" data-wf-form="discover">${select("discoverModel", "Local model", [["", "Choose a model"], ...data.models.map(m => [m.alias, m.label || m.alias])], data.models[0]?.alias)}${check("discoverBrain", "Use my personal Brain notes and goals for suggestions", true)}<button class="primary" ${busy ? "disabled" : ""}>${busy ? "Finding ideas…" : "Find suggestions"}</button></form><form class="wf-discover-form" data-wf-form="discoverySettings">${check("discoveryEnabled", "Suggest new routines automatically once a day", settings.enabled)}${select("discoveryModel", "Local model for daily suggestions", [["", "Choose a model"], ...data.models.map(m => [m.alias, m.label || m.alias])], settings.model || data.models[0]?.alias)}${check("discoveryBrain", "Include my personal Brain notes and goals", settings.includeBrain)}<button>Save suggestion settings</button><p class="hub-help">Runs while KAI is open. Suggestions wait for your review and never enable a workflow automatically.${settings.lastAt ? " Last checked: " + date(settings.lastAt) : ""}</p>${settings.error ? `<p class="error">${esc(settings.error)}</p>` : ""}</form><div class="wf-templates">${suggestions.map(s => `<article class="hub-card"><span class="hub-badge">Suggested for you</span><h3>${esc(s.name)}</h3><p>${esc(s.request)}</p><p><b>Why:</b> ${esc(s.reason)}</p><div class="hub-actions">${btn("Build this", "buildSuggestion", s.id, "primary")}${btn("Dismiss", "dismiss", s.id)}</div></article>`).join("") || empty("Ideas start with your context", "Choose a local model and find suggestions. Nothing is saved or enabled until you review it.")}</div>`; }
  function builder() {
    const report = M.validateGraph(draft.graph), last = data.runs.find(r => r.id === runId), readOnly = !!runId;
    return `<div class="wf-builder-header">${btn("← Back", "back")}<div class="wf-builder-title"><h2>${esc(draft.name)}</h2><small>${readOnly ? "Run snapshot · " + last?.status : dirty() ? "Unsaved changes" : draft.id ? "Saved workflow" : "New workflow"}</small></div><div class="wf-builder-actions">${btn("Copilot", "inspector", "copilot", inspector === "copilot" ? "active" : "")}${!readOnly ? btn("Settings", "inspector", "settings") + btn("Save workflow", "save", "", "primary") : ""}${draft.id && !draft.draft && !readOnly ? btn("Run", "run", draft.id) : ""}</div></div><div class="wf-builder-tools"><div>${btn("Undo", "undo")}${btn("Redo", "redo")}${btn("Add node", "palette")}${btn("Auto arrange", "arrange")}</div><div>${btn("Validate", "validate")}${draft.id && !draft.draft ? btn("Preview", "preview", draft.id) : ""}${btn("Run details", "inspector", "runs")}</div></div>${report.errors.length || invalid ? `<div class="wf-validation error">${esc(invalid || report.errors[0].message)}${report.errors.length > 1 ? ` (+${report.errors.length - 1} more)` : ""}</div>` : `<div class="wf-canvas-hint">${linking ? "Choose the input dot on the destination node. Escape cancels." : "Drag nodes to arrange them. Connect an output to another node's input. Scroll to pan; Ctrl + scroll to zoom."}</div>`}<div class="wf-builder-body"><aside class="wf-palette" aria-label="Node library"><input id="wf-node-search" placeholder="Find a node" aria-label="Find a node"/>${["Start", "Actions", "Logic", "Finish"].map(group => `<div class="wf-palette-group"><h3>${group}</h3>${M.catalog.filter(n => n.group === group).map(n => `<button type="button" data-wf="add" data-id="${n.type}" title="${esc(n.description)}"><span>${n.icon}</span>${n.name}</button>`).join("")}</div>`).join("")}</aside><div class="wf-viewport" tabindex="0" role="region" aria-label="Workflow canvas"><div class="wf-stage"><svg class="wf-edges" aria-label="Node connections"></svg><div class="wf-nodes">${draft.graph.nodes.map(nodeHTML).join("")}</div></div><div class="wf-canvas-controls">${btn("−", "zoomOut") }<span id="wf-zoom">${Math.round(zoom * 100)}%</span>${btn("+", "zoomIn")}${btn("Fit", "fit")}</div></div><aside class="wf-inspector" aria-label="Workflow inspector">${inspectorHTML()}</aside></div>${last && ["waiting", "running", "interrupted"].includes(last.status) ? `<div class="wf-running-strip"><span>${esc(last.name)} · ${esc(last.status)}</span>${last.status === "waiting" ? btn("Review & resume", "resume", last.id, "primary") : ""}${btn("Cancel run", "cancel", last.id)}</div>` : ""}`;
  }
  function nodeHTML(n) { const run = data.runs.find(r => r.id === runId), state = run?.frames?.root?.states?.[n.id]?.status || "", outputs = M.ports(n).filter(p => p !== "error" || n.config.onError === "route"); return `<article class="wf-node ${selected === n.id ? "selected" : ""} ${esc(state)}" data-node="${esc(n.id)}" style="left:${n.position.x}px;top:${n.position.y}px" tabindex="0" aria-label="${esc(n.label)} node"><button class="wf-input-port" data-wf="connectTo" data-id="${esc(n.id)}" aria-label="Connect to ${esc(n.label)}" title="Input"></button><div class="wf-node-heading" data-drag-node="${esc(n.id)}"><span class="wf-node-icon type-${n.type}">${M.meta(n.type)?.icon || "◇"}</span><div><strong>${esc(n.label)}</strong><small>${esc(M.meta(n.type)?.name || n.type)}${state ? " · " + state : ""}</small></div></div><p>${esc(summary(n))}</p><div class="wf-output-ports">${outputs.map(p => `<button type="button" data-wf="connectFrom" data-id="${esc(n.id)}" data-port="${esc(p)}" aria-label="${esc(n.label)} ${esc(p)} output">${esc(p)}<i></i></button>`).join("")}</div></article>`; }
  function summary(n) { const c = n.config; return (n.type === "trigger" ? triggerLabel(c) : n.type === "agent" ? c.prompt : n.type === "tool_call" ? data.connections.find(x => x.id === c.connectionId)?.name || "Choose an app action" : n.type === "http_request" ? (c.method || "GET") + " " + (c.connectionId ? "Saved API connection" : c.url) : n.type === "memory" ? c.operation + " · " + (c.query || c.title || "Brain") : n.type === "loop" ? "Up to " + c.maxIterations + " iterations" : n.type === "sub_workflow" ? data.workflows.find(w => w.id === c.workflowId)?.name || "Choose a workflow" : c.expression || c.text || c.source || M.meta(n.type)?.description || "").slice(0, 100); }
  function inspectorHTML() {
    if (inspector === "copilot") return `<h3>Build with KAI</h3><p class="hub-help">Describe what you want to add or change. Review the proposed graph before applying it.</p><form data-wf-form="assist">${select("assistModel", "Local model", [["", "Choose a model"], ...data.models.map(m => [m.alias, m.label || m.alias])], draft.model || data.models[0]?.alias)}${field("assistRequest", "What should this workflow do?", "", "area")}<button class="primary" ${busy || runId ? "disabled" : ""}>${busy ? "Designing…" : "Suggest changes"}</button></form>${proposal ? `<div class="wf-proposal"><h4>${esc(proposal.proposal.name)}</h4><p>${esc(proposal.proposal.description)}</p><p>${proposal.proposal.graph.nodes.length} nodes · ${proposal.proposal.graph.edges.length} connections</p>${proposal.report.errors.map(e => `<p class="error">${esc(e.message)}</p>`).join("")}${btn("Apply to canvas", "applyProposal", "", "primary")}${btn("Dismiss proposal", "dismissProposal")}</div>` : ""}`;
    if (inspector === "settings") return `<h3>Workflow settings</h3><fieldset ${runId ? "disabled" : ""}>${field("name", "Workflow name", draft.name)}${field("description", "Purpose", draft.description, "area")}${select("model", "Default local model", [["", "Choose a model"], ...data.models.map(m => [m.alias, m.label || m.alias])], draft.model)}${check("enabled", "Enable automatic triggers", draft.enabled)}<p class="hub-help">Schedules and watches run while KAI is open. App writes and Brain changes pause for your review.</p>${btn("Save as draft", "saveDraft")}</fieldset><details><summary>Workflow JSON</summary><textarea id="wf-document" rows="14" spellcheck="false">${esc(JSON.stringify(draft, null, 2))}</textarea>${!runId ? btn("Apply JSON", "applyJSON") : ""}</details>`;
    if (inspector === "runs") { const list = data.runs.filter(r => r.workflowId === draft.id).slice(0, 8); return `<h3>Recent runs</h3>${list.map(r => `<button class="wf-run-link" data-wf="selectRun" data-id="${esc(r.id)}"><b>${esc(r.status)}</b><small>${date(r.startedAt)}</small></button>`).join("") || `<p class="hub-help">Save and run this workflow to inspect it here.</p>`}${runId ? runCard(data.runs.find(r => r.id === runId)) : ""}`; }
    const n = currentNode(); if (!n) return `<h3>Choose a node</h3><p class="hub-help">Select a node to edit its settings and see its connections.</p>`;
    const c = n.config, f = (key, label, kind = "text", hint = "") => field("config." + key, label, c[key] ?? "", kind, hint), s = (key, label, choices) => select("config." + key, label, choices, c[key]), b = (key, label) => check("config." + key, label, c[key]);
    let fields = "";
    if (n.type === "trigger") {
      fields += s("kind", "When to run", [["manual", "On demand"], ["schedule", "On a schedule"], ["app_change", "When an app's data changes"], ["source_change", "When a Brain source changes"], ["app_event", "When an app event arrives"]]);
      if (c.kind === "schedule") { const v = c.schedule || {}, sf = (k, label, kind = "text") => field("config.schedule." + k, label, v[k] ?? "", kind); fields += select("config.schedule.kind", "Schedule", [["hourly", "Every hour"], ["every6h", "Every 6 hours"], ["daily", "Daily"], ["weekly", "Weekly"], ["interval", "Custom interval"], ["at", "Once at a date/time"], ["cron", "Cron expression"]], v.kind || "daily"); if (["daily", "weekly"].includes(v.kind)) fields += `<div class="wf-field-pair">${sf("hour", "Hour (0–23)", "number")}${sf("minute", "Minute (0–59)", "number")}</div>`; if (v.kind === "weekly") fields += select("config.schedule.day", "Day", [[0, "Sunday"], [1, "Monday"], [2, "Tuesday"], [3, "Wednesday"], [4, "Thursday"], [5, "Friday"], [6, "Saturday"]], v.day ?? 1); if (v.kind === "interval") fields += sf("minutes", "Every N minutes", "number"); if (v.kind === "at") fields += sf("at", "Date and time (ISO, with offset)"); if (v.kind === "cron") fields += sf("expression", "Cron: minute hour day month weekday"); if (["daily", "weekly", "cron"].includes(v.kind)) fields += sf("timezone", "Time zone (blank = this computer)"); }
      if (c.kind === "app_change") fields += connectionFields(n, true);
      if (c.kind === "app_event") { const schema = (eventChoices[c.connectionId] || []).find(t => t.slug === c.triggerSlug)?.config; fields += s("connectionId", "Connected app account", [["", "Choose an app"], ...data.connections.filter(x => x.provider === "composio" && x.enabled && x.allowSync).map(x => [x.id, x.name])]) + btn("Load available events", "loadEvents", c.connectionId) + s("triggerSlug", "Event type", [["", "Choose an event"], ...(eventChoices[c.connectionId] || (c.triggerSlug ? [{slug:c.triggerSlug,name:c.triggerSlug}] : [])).map(x => [x.slug, x.name])]) + (schema?.properties ? Object.entries(schema.properties).map(([key, p]) => field("config.triggerConfig." + key, key.replace(/_/g, " ") + ((schema.required || []).includes(key) ? " *" : ""), c.triggerConfig?.[key] ?? "", ["object", "array"].includes(p.type) ? "json" : ["boolean", "number", "integer"].includes(p.type) ? "value" : "text", esc(p.description || ""))).join("") : f("triggerConfig", "Event settings (JSON)", "json")) + `<p class="hub-help">Enable the workflow to register this event. KAI uses your account server to receive signed events. Existing Composio webhook destinations are kept.</p>`; }
      if (c.kind === "source_change") fields += s("sourceId", "Brain source", [["", "Choose a source"], ...data.sources.map(x => [x.id, x.name])]);
      if (["app_change", "source_change"].includes(c.kind)) fields += f("intervalMinutes", "Check every N minutes", "number", "The first check establishes a baseline; later changes start a run.");
      fields += `<details><summary>Run input fields</summary>${f("inputFields", "Fields (name, type, required)", "json")}</details>`;
    }
    if (n.type === "agent") fields += s("profile", "Agent role", ["assistant", "planner", "researcher", "writer", "analyst"]) + s("model", "Local model", [["", "Use workflow default"], ...data.models.map(m => [m.alias, m.label || m.alias])]) + f("prompt", "Instructions", "area") + f("maxTurns", "Maximum turns", "number") + `<details><summary>Selected read tools</summary><p class="hub-help">Choose read actions from Connections. Outbound changes use separate App action nodes.</p>${data.connections.filter(x => x.enabled && x.allowSync).flatMap(conn => conn.operations.filter(o => o.method === "GET").map(o => `<label class="wf-check"><input type="checkbox" data-read-tool="${esc(conn.id)}" data-operation="${esc(o.id)}" ${(c.tools || []).some(t => t.connectionId === conn.id && t.operationId === o.id) ? "checked" : ""}/><span>${esc(conn.name)} · ${esc(o.name)}</span></label>`)).join("") || "No background read actions selected in Connections yet."}</details>`;
    if (n.type === "tool_call") fields += connectionFields(n);
    if (n.type === "http_request") { fields += s("connectionId", "Authentication", [["", "Public endpoint (no credentials)"], ...data.connections.filter(x => x.enabled && x.provider !== "composio").map(x => [x.id, x.name])]); if (c.connectionId) fields += connectionFields(n, false, true); else fields += s("method", "Method", ["GET", "POST", "PUT", "PATCH", "DELETE"]) + f("url", "Endpoint URL") + f("headers", "Headers (Accept / Content-Type)", "json") + f("body", "Request body", "json"); }
    if (n.type === "code") fields += `<p class="hub-help">JavaScript with <code>items</code>, <code>item</code>, <code>input</code>, and <code>nodes</code>. Return JSON data. Files and network are unavailable.</p>` + f("source", "JavaScript", "code");
    if (n.type === "sub_workflow") fields += s("workflowId", "Saved workflow", [["", "Choose a workflow"], ...data.workflows.filter(w => w.id !== draft.id && !w.draft).map(w => [w.id, w.name])]);
    if (n.type === "memory") { fields += s("operation", "Brain action", [["search", "Search memories"], ["recall", "Recall context"], ["people", "Find people"], ["goals", "Read active goals"], ["remember", "Remember (review first)"], ["forget", "Forget a note (review first)"]]); if (["search", "recall", "people"].includes(c.operation)) fields += f("query", "Search for") + f("limit", "Maximum matches", "number"); if (c.operation === "remember") fields += f("title", "Memory title") + f("value", "What to remember", "area"); if (c.operation === "forget") fields += s("noteId", "Personal note", [["", "Choose a note"], ...data.notes.filter(n => !n.sourceId).map(n => [n.id, n.title])]); }
    if (n.type === "approval") fields += f("text", "What should be reviewed?", "area") + `<p class="hub-help">Connect Approved and Rejected outputs to the next steps.</p>`;
    if (n.type === "condition") fields += f("expression", "Value or expression") + s("operator", "Condition", [["truthy", "Is true / has a value"], ["equals", "Equals"], ["contains", "Contains"], ["greater", "Greater than"], ["less", "Less than"], ["empty", "Is empty"]]) + (!["truthy", "empty"].includes(c.operator) ? f("value", "Compare with") : "");
    if (n.type === "switch") fields += f("expression", "Route by expression") + f("cases", "Case names (JSON array)", "json");
    if (n.type === "merge") fields += s("mode", "Combine branches", [["append", "Append all items"], ["position", "Combine by position"], ["key", "Combine by matching key"]]) + (c.mode === "key" ? f("key", "Matching field") : "") + `<p class="hub-help">Use distinct destination input names (A and B) for position or key merges.</p>`;
    if (n.type === "split_out") fields += f("field", "Array expression") + b("keepFields", "Keep the original item's fields");
    if (n.type === "transform") fields += f("set", "Field mapping (JSON)", "json", 'For example: {"title":"=item.json.title"}') + b("keepFields", "Keep other fields");
    if (n.type === "output_parser") fields += s("format", "Output format", ["json", "text", "csv"]) + f("field", "Value to parse") + f("required", "Required fields (comma-separated)");
    if (n.type === "dedup") fields += f("key", "Stable item key", "text", "For example =item.id. Missing keys fail the node.") + s("scope", "Remember seen items", [["workflow", "Across workflow runs"], ["run", "Within this batch"]]);
    if (n.type === "loop") fields += f("maxIterations", "Maximum iterations (1–50)", "number") + f("condition", "Continue while (optional expression)") + s("onExceeded", "At the limit", [["continue", "Continue through Done"], ["error", "Fail the run"]]) + `<p class="hub-help">Connect Body to the repeated steps, then connect their last output back to this loop's input.</p>`;
    if (n.type === "output") fields += f("text", "Result", "area") + b("saveChat", "Also save the answer in Chat history");
    if (["agent", "tool_call", "http_request", "memory", "sub_workflow"].includes(n.type)) fields += s("execution", "Process input", [["once", "Once for the whole input"], ["per_item", "Once for each item"]]);
    const edges = draft.graph.edges.filter(e => e.from === n.id || e.to === n.id);
    return `<div class="wf-inspector-heading"><span class="wf-node-icon">${M.meta(n.type)?.icon}</span><h3>${esc(M.meta(n.type)?.name)}</h3></div><fieldset ${runId ? "disabled" : ""}>${field("label", "Node name", n.label)}${fields}<details class="wf-advanced"><summary>Errors, review & sample data</summary>${s("onError", "If this node fails", [["stop", "Stop run"], ["continue", "Continue with error data"], ["route", "Follow Error output"]])}${f("retries", "Read / compute retries (0–2)", "number")}${f("timeoutSeconds", "Model timeout (5–180 seconds)", "number")}${b("requireApproval", "Review before this node")}${f("sampleOutput", "Simulated output for Preview", "json")}</details><details class="wf-advanced"><summary>Data from earlier nodes</summary><p class="hub-help">Use =item.field, =item.json.field, =nodes.ID.text, or {{previous}}. Expressions use JavaScript.</p>${draft.graph.nodes.filter(x => x.id !== n.id).map(x => `<button type="button" class="wf-expression" data-wf="copyExpr" data-id="${esc(x.id)}">=nodes.${esc(x.id)}.text</button>`).join("")}</details><h4>Connections</h4><div class="wf-edge-list">${edges.map(e => `<div><span>${esc(e.from)} <b>${esc(e.port)}</b> → ${esc(e.to)} <small>${esc(e.input)}</small></span>${btn("×", "removeEdge", e.id)}</div>`).join("") || `<p class="hub-help">Connect this node on the canvas.</p>`}</div><div class="wf-edge-form">${select("linkPort", "Output", M.ports(n), "main")}${select("linkTarget", "Next node", [["", "Choose a node"], ...draft.graph.nodes.filter(x => x.id !== n.id && x.type !== "trigger").map(x => [x.id, x.label])], "")}${field("linkInput", "Destination input", "main")}${btn("Connect nodes", "addEdge")}</div><div class="hub-actions">${btn("Duplicate node", "duplicateNode")}${n.type !== "trigger" ? btn("Delete node", "deleteNode") : ""}</div></fieldset>`;
  }
  function connectionFields(n, read = false, hideConnection = false) {
    const c = n.config, connections = data.connections.filter(x => x.enabled && (!read || x.allowSync)), conn = connections.find(x => x.id === c.connectionId), op = conn?.operations.find(o => o.id === c.operationId);
    return `${!hideConnection ? select("config.connectionId", "Connected account", [["", "Choose an account"], ...connections.map(x => [x.id, x.name])], c.connectionId) : ""}${select("config.operationId", "Action", [["", "Choose an action"], ...(conn?.operations || []).filter(o => !read || o.method === "GET").map(o => [o.id, o.name + (o.method === "GET" ? " · read" : " · review")])], c.operationId)}${op?.schema ? Object.entries(op.schema.properties || {}).slice(0, 25).map(([key, p]) => field("config.variables." + key, key.replace(/_/g, " ") + ((op.schema.required || []).includes(key) ? " *" : ""), c.variables?.[key] ?? (p.type === "object" ? {} : p.type === "array" ? [] : ""), ["object", "array"].includes(p.type) ? "json" : ["number", "integer", "boolean"].includes(p.type) ? "value" : "text", esc(String(p.description || "").slice(0, 180)))).join("") : field("config.variables", "Path variables (JSON)", c.variables || {}, "json")}${conn?.provider !== "composio" && op?.method !== "GET" ? field("config.body", "Request body (JSON)", c.body || {}, "json") : ""}`;
  }
  function modalHTML() { const w = data.workflows.find(w => w.id === modal.id); return `<div class="wf-modal-backdrop"><section class="wf-modal" role="dialog" aria-modal="true" aria-label="Start workflow"><div class="wf-heading"><h3>${esc(w?.name || "Start workflow")}</h3>${btn("×", "closeModal")}</div><form data-wf-form="run"><label class="wf-field"><span>Run input (optional)</span><textarea name="input" rows="6" placeholder="A topic, prompt, or JSON input"></textarea></label>${(w?.graph?.nodes.find(n => n.type === "trigger")?.config.inputFields || []).length ? `<p class="hub-help">Enter JSON with these fields: ${w.graph.nodes.find(n => n.type === "trigger").config.inputFields.map(f => esc(f.name + " (" + f.type + (f.required ? ", required" : "") + ")")).join(", ")}</p>` : ""}<p class="hub-help">${modal.preview ? "Preview uses sample outputs for model, app, and memory nodes. No requests or changes are made." : "Writes and Brain changes pause for your review."}</p><button class="primary">${modal.preview ? "Start preview" : "Start run"}</button></form></section></div>`; }
  function paint() {
    const stage = host.querySelector(".wf-stage"); if (!stage || !draft) return;
    stage.style.transform = `translate(${pan.x}px,${pan.y}px) scale(${zoom})`;
    const svg = host.querySelector(".wf-edges"); svg.innerHTML = draft.graph.edges.map(e => {
      const a = draft.graph.nodes.find(n => n.id === e.from), b = draft.graph.nodes.find(n => n.id === e.to); if (!a || !b) return "";
      const origin = stage.getBoundingClientRect(), from = host.querySelector(`[data-wf="connectFrom"][data-id="${a.id}"][data-port="${e.port}"] i`)?.getBoundingClientRect(), to = host.querySelector(`[data-wf="connectTo"][data-id="${b.id}"]`)?.getBoundingClientRect();
      const x1 = from ? (from.x + from.width / 2 - origin.x) / zoom : a.position.x + 240, y1 = from ? (from.y + from.height / 2 - origin.y) / zoom : a.position.y + 112, x2 = to ? (to.x + to.width / 2 - origin.x) / zoom : b.position.x, y2 = to ? (to.y + to.height / 2 - origin.y) / zoom : b.position.y + 53;
      const d = `M${x1},${y1} C${x1 + 70},${y1} ${x2 - 70},${y2} ${x2},${y2}`;
      return `<g class="wf-edge" data-wf="selectEdge" data-id="${esc(e.id)}"><path class="wf-edge-hit" d="${d}"/><path d="${d}"/><text x="${(x1 + x2) / 2}" y="${(y1 + y2) / 2 - 7}">${esc(e.port === "main" ? "" : e.port)}</text></g>`;
    }).join(""); const label = host.querySelector("#wf-zoom"); if (label) label.textContent = Math.round(zoom * 100) + "%";
  }
  function fit() { const rect = host.querySelector(".wf-viewport")?.getBoundingClientRect(); if (!rect || !draft.graph.nodes.length) return; const minX = Math.min(...draft.graph.nodes.map(n => n.position.x)), minY = Math.min(...draft.graph.nodes.map(n => n.position.y)), width = Math.max(...draft.graph.nodes.map(n => n.position.x + 260)) - minX, height = Math.max(...draft.graph.nodes.map(n => n.position.y + 140)) - minY; zoom = Math.max(.18, Math.min(1, (rect.width - 60) / width, (rect.height - 60) / height)); pan = { x: (rect.width - width * zoom) / 2 - minX * zoom, y: 25 - minY * zoom }; paint(); }
  function setValue(target, path, value) { const parts = path.split("."); for (const key of parts) if (["__proto__", "constructor", "prototype"].includes(key)) throw Error("Unsupported field."); for (const key of parts.slice(0, -1)) { if (!target[key] || typeof target[key] !== "object") target[key] = {}; target = target[key]; } target[parts.at(-1)] = value; }
  function readField(el) { return el.dataset.format === "bool" ? el.checked : el.dataset.format === "number" ? Number(el.value) : el.dataset.format === "value" ? (el.value.startsWith("=") ? el.value : JSON.parse(el.value)) : el.dataset.format === "json" ? JSON.parse(el.value || "null") : el.value; }
  function input(e) {
    const el = e.target;
    if (el.id === "wf-filter") { filter = el.value; const position = el.selectionStart; draw(); const input = host.querySelector("#wf-filter"); input.focus(); input.setSelectionRange(position, position); return; }
    if (el.id === "wf-node-search") { for (const b of host.querySelectorAll('[data-wf="add"]')) b.hidden = !b.textContent.toLowerCase().includes(el.value.toLowerCase()); return; }
    if (!el.dataset.field || !draft || runId || /^(assist|discover|link|run)/.test(el.dataset.field)) return;
    try {
      const path = el.dataset.field, target = inspector === "settings" ? draft : currentNode(); if (!target) return;
      if (el.dataset.format === "json") readField(el); // Keep invalid JSON text available for correction.
      if (!el.dataset.history) { history(); el.dataset.history = "1"; }
      setValue(target, path, readField(el)); invalid = ""; const title = host.querySelector(".wf-builder-title small"); if (title) title.textContent = "Unsaved changes";
    } catch { invalid = "Enter valid JSON before saving this node."; notice(invalid, true); }
  }
  function change(e) {
    const el = e.target;
    if (el.dataset.field === "runWorkflow") { runFilter = el.value; draw(); return; } if (el.dataset.field === "runStatus") { runStatus = el.value; draw(); return; }
    if (el.dataset.readTool && currentNode() && !runId) { history(); const tools = currentNode().config.tools ||= []; const key = el.dataset.readTool, op = el.dataset.operation; currentNode().config.tools = tools.filter(t => !(t.connectionId === key && t.operationId === op)); if (el.checked) currentNode().config.tools.push({ connectionId: key, operationId: op }); return; }
    input(e);
    if (!draft || runId || !el.dataset.field || /^(assist|discover|link|run)/.test(el.dataset.field)) return;
    if (["config.connectionId", "config.operationId"].includes(el.dataset.field)) { if (el.dataset.field === "config.connectionId") { currentNode().config.operationId = ""; delete currentNode().config.triggerId; delete currentNode().config.triggerSlug; } currentNode().config.variables = {}; }
    if (el.dataset.field === "config.kind" && currentNode()?.type === "trigger") { currentNode().config.schedule ||= { kind: "daily", hour: 9, minute: 0, day: 1 }; currentNode().config.intervalMinutes ||= 5; }
    if (el.dataset.field === "config.schedule.kind") { const s = currentNode().config.schedule; s.hour ??= 9; s.minute ??= 0; s.day ??= 1; s.minutes ??= 30; s.expression ||= "0 9 * * 1-5"; }
    if (!invalid) { const scroll = host.querySelector(".wf-inspector")?.scrollTop || 0; draw(); host.querySelector(".wf-inspector").scrollTop = scroll; }
  }
  async function click(e) {
    const button = e.target.closest("[data-wf]");
    if (!button) { const n = e.target.closest("[data-node]"); if (n && !e.target.closest("input,textarea,select")) { selected = n.dataset.node; inspector = "node"; draw(); } return; }
    const action = button.dataset.wf, id = button.dataset.id; if (busy && !["cancel", "closeModal"].includes(action)) return;
    try {
      if (runId && ["add", "duplicateNode", "deleteNode", "removeEdge", "addEdge", "connectTo", "connectFrom", "undo", "redo", "applyJSON", "save", "saveDraft", "arrange"].includes(action)) return notice("This canvas is a saved run snapshot. Open the workflow to edit it.");
      if (action === "loadEvents") { const result = await api.manage("workflowEventTypes", { connectionId: id }); eventChoices[id] = result.items; draw(); }
      if (action === "new") newFlow();
      if (action === "edit") open(data.workflows.find(w => w.id === id));
      if (action === "duplicate") { const w = clone(data.workflows.find(w => w.id === id)); delete w.id; w.name += " copy"; w.enabled = false; delete w.legacyTask; open(w); }
      if (action === "template") open(M.template(id, data.models[0]?.alias || "", data.connections.find(c => c.enabled)));
      if (action === "templates") await api.navigate("templates");
      if (action === "back") { if (!runId && dirty() && !window.confirm("Discard unsaved workflow changes?")) return; draft = null; runId = ""; linking = null; await refresh(); draw(); }
      if (action === "inspector") { inspector = id; draw(); }
      if (action === "palette") host.querySelector(".wf-palette")?.classList.toggle("show");
      if (action === "add") { if (id === "trigger" && draft.graph.nodes.some(n => n.type === "trigger")) throw Error("A workflow has one trigger. Select it to change how the workflow starts."); commit(() => { const anchor = currentNode()?.position || { x: 80, y: 70 }; selected = "n" + Date.now().toString(36); const position = { x: anchor.x, y: anchor.y + 180 }; while (draft.graph.nodes.some(n => Math.abs(n.position.x - position.x) < 260 && Math.abs(n.position.y - position.y) < 160)) position.y += 180; const n = M.node(id, selected, position); if (id === "agent") n.config.model = draft.model; draft.graph.nodes.push(n); inspector = "node"; }); }
      if (action === "duplicateNode") { const n = currentNode(); if (!n || n.type === "trigger") return; commit(() => { const copied = clone(n); copied.id = "n" + Date.now().toString(36); copied.position.x += 40; copied.position.y += 160; draft.graph.nodes.push(copied); selected = copied.id; }); }
      if (action === "deleteNode") { const n = currentNode(); if (!n || n.type === "trigger") return; commit(() => { draft.graph.nodes = draft.graph.nodes.filter(x => x.id !== n.id); draft.graph.edges = draft.graph.edges.filter(x => x.from !== n.id && x.to !== n.id); selected = ""; }); }
      if (action === "removeEdge") commit(() => { draft.graph.edges = draft.graph.edges.filter(e => e.id !== id); });
      if (action === "selectEdge") { const edge = draft.graph.edges.find(e => e.id === id); if (edge) { selected = edge.from; inspector = "node"; draw(); notice("Connection selected. Remove it in the node's Connections list."); } }
      if (action === "connectFrom") { linking = { from: id, port: button.dataset.port }; notice("Choose the destination node's input dot."); }
      if (action === "connectTo" && linking) { connect(linking.from, id, linking.port); linking = null; }
      if (action === "addEdge") { const get = key => host.querySelector(`[data-field="${key}"]`)?.value; if (!get("linkTarget")) throw Error("Choose the destination node."); connect(selected, get("linkTarget"), get("linkPort"), get("linkInput")); }
      if (action === "undo" && undo.length) { redo.push(clone(draft)); draft = undo.pop(); draw(); } if (action === "redo" && redo.length) { undo.push(clone(draft)); draft = redo.pop(); draw(); }
      if (action === "zoomIn") { zoom = Math.min(1.8, zoom * 1.2); paint(); } if (action === "zoomOut") { zoom = Math.max(.18, zoom / 1.2); paint(); } if (action === "fit") fit();
      if (action === "arrange") { commit(() => { const levels = new Map([[draft.graph.nodes.find(n => n.type === "trigger")?.id, 0]]); for (let i = 0; i < draft.graph.nodes.length; i++) for (const edge of draft.graph.edges) if (levels.has(edge.from) && !levels.has(edge.to)) levels.set(edge.to, levels.get(edge.from) + 1); const counts = {}; for (const n of draft.graph.nodes) { const level = levels.get(n.id) ?? 0; n.position = { x: 60 + (counts[level] || 0) * 310, y: 50 + level * 170 }; counts[level] = (counts[level] || 0) + 1; } }); fit(); }
      if (action === "validate") { const report = await api.manage("workflowValidate", draft); notice(report.errors.length ? report.errors.map(e => e.message).join(" ") : "The flow is valid." + (report.nextRunAt ? " Next scheduled run: " + date(report.nextRunAt) : "") + (report.warnings.length ? " " + report.warnings.map(w => w.message).join(" ") : ""), !!report.errors.length); }
      if (["save", "saveDraft"].includes(action)) { if (invalid) throw Error(invalid); busy = true; const w = await api.manage(action === "saveDraft" ? "workflowDraft" : "workflow", draft); await refresh(); draft = M.fromLegacy(w); savedJSON = JSON.stringify(draft); draw(); notice(action === "saveDraft" ? "Draft saved. Review it before enabling or running." : "Workflow saved."); }
      if (action === "toggle") { const w = data.workflows.find(w => w.id === id); await api.manage("workflowEnabled", { id, enabled: !w.enabled }); await refresh(); draw(); }
      if (action === "delete") { if (!window.confirm("Delete this workflow and its run history?")) return; await api.manage("removeWorkflow", { id }); await refresh(); draw(); }
      if (action === "import") { const w = await api.manage("importWorkflow"); await refresh(); if (w) open(w); }
      if (action === "export") await api.manage("exportWorkflow", { id });
      if (action === "run" || action === "preview") { if (draft && !runId && dirty()) throw Error("Save the changes before running this workflow."); modal = { id, preview: action === "preview" }; draw(); host.querySelector('.wf-modal textarea')?.focus(); }
      if (action === "closeModal") { modal = null; draw(); }
      if (action === "history") { draft = null; runFilter = id; await api.navigate("runs"); }
      if (["runCanvas", "selectRun"].includes(action)) { const run = data.runs.find(r => r.id === id); open(run.spec); runId = id; inspector = "runs"; draw(); fit(); }
      if (action === "resume") { await api.manage("resume", { id }); await refresh(); draw(); }
      if (action === "reject") { await api.manage("workflowReject", { id }); await refresh(); draw(); }
      if (action === "cancel") { await api.manage("cancelRun", { id }); await refresh(); draw(); }
      if (action === "refresh") { await refresh(); draw(); }
      if (action === "quickBuild") { const request = host.querySelector("#wf-quick-prompt").value; newFlow(); inspector = "copilot"; draw(); host.querySelector('[data-field="assistRequest"]').value = request; }
      if (action === "applyProposal" && proposal) { commit(() => { draft = { ...proposal.proposal, ...(draft.id ? { id: draft.id } : {}), enabled: false }; selected = draft.graph.nodes[0]?.id; proposal = null; inspector = "node"; }); fit(); }
      if (action === "dismissProposal") { proposal = null; draw(); }
      if (action === "applyJSON") { const raw = JSON.parse(host.querySelector("#wf-document").value), doc = M.importDocument(raw); commit(() => { draft = { ...doc, ...(draft.id ? { id: draft.id } : {}) }; }); }
      if (action === "copyExpr") { const text = "=nodes." + id + ".text"; await navigator.clipboard.writeText(text); notice("Copied " + text); }
      if (action === "dismiss") { await api.manage("workflowDismiss", { id }); await refresh(); draw(); }
      if (action === "buildSuggestion") { const suggestion = data.workflowState.suggestions.find(s => s.id === id); open(M.template(suggestion.template, data.models[0]?.alias || "", data.connections.find(c => c.enabled))); draft.name = suggestion.name; inspector = "copilot"; draw(); host.querySelector('[data-field="assistRequest"]').value = suggestion.request; }
    } catch (error) { notice(error.message, true); } finally { busy = false; poll(); }
  }
  function connect(from, to, port = "main", input = "main") { if (draft.graph.nodes.find(n => n.id === to)?.type === "trigger") throw Error("Connect to an action or logic node, not the trigger."); const edge = M.edge(from, to, port, input || "main"); if (draft.graph.edges.some(e => e.id === edge.id)) throw Error("These ports are already connected."); commit(() => draft.graph.edges.push(edge)); }
  async function submit(e) {
    const form = e.target.closest("[data-wf-form]"); if (!form) return; e.preventDefault(); if (busy) return; busy = true;
    const button = form.querySelector('button:not([type="button"])'); if (button) button.disabled = true;
    try {
      const type = form.dataset.wfForm, get = key => form.querySelector(`[data-field="${key}"]`);
      if (type === "run") { const m = modal, input = form.elements.input.value; const result = await api.manage(m.preview ? "workflowPreview" : "run", { id: m.id, input }); modal = null; await refresh(); draft = null; runId = ""; runFilter = m.id; await api.navigate("runs"); notice(m.preview ? "Preview started with simulated capability outputs." : "Workflow started."); }
      if (type === "assist") { notice("KAI is designing the flow…"); proposal = await api.manage("workflowAssist", { request: get("assistRequest").value, model: get("assistModel").value, workflow: draft }); draw(); notice("Review the proposed changes, then apply them to the canvas."); }
      if (type === "discoverySettings") { await api.manage("workflowDiscoverySettings", { enabled: get("discoveryEnabled").checked, model: get("discoveryModel").value, includeBrain: get("discoveryBrain").checked }); await refresh(); draw(); }
      if (type === "discover") { notice("Looking for useful routines…"); await api.manage("workflowDiscover", { model: get("discoverModel").value, includeBrain: get("discoverBrain").checked }); await refresh(); draw(); }
    } catch (error) { notice(error.message, true); } finally { busy = false; if (button) button.disabled = false; host.querySelectorAll('[data-wf-form="assist"] button,[data-wf-form="discover"] button').forEach(b => { b.disabled = false; b.textContent = b.closest('[data-wf-form="assist"]') ? "Suggest changes" : "Find suggestions"; }); poll(); }
  }
  function pointerdown(e) {
    if (!draft || e.button !== 0) return;
    const heading = e.target.closest("[data-drag-node]"), viewport = e.target.closest(".wf-viewport"), port = e.target.closest('[data-wf="connectFrom"]');
    if (port && !runId) { const from = port.dataset.id, output = port.dataset.port; const finish = ev => { window.removeEventListener("pointerup", finish); const target = document.elementFromPoint(ev.clientX, ev.clientY)?.closest('[data-wf="connectTo"]'); if (target) { try { connect(from, target.dataset.id, output); linking = null; } catch (error) { notice(error.message, true); } } }; window.addEventListener("pointerup", finish, { once: true }); return; }
    if (heading && !runId) {
      e.preventDefault(); const n = draft.graph.nodes.find(n => n.id === heading.dataset.dragNode), start = { x: e.clientX, y: e.clientY, ...n.position }, old = { ...n.position }; history(); selected = n.id;
      const move = ev => { n.position = { x: Math.max(0, Math.min(6000, Math.round((old.x + (ev.clientX - e.clientX) / zoom) / 10) * 10)), y: Math.max(0, Math.min(12000, Math.round((old.y + (ev.clientY - e.clientY) / zoom) / 10) * 10)) }; const nodeEl = host.querySelector(`[data-node="${n.id}"]`); if (nodeEl) { nodeEl.style.left = n.position.x + "px"; nodeEl.style.top = n.position.y + "px"; } paint(); };
      const up = () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up); inspector = "node"; draw(); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up, { once: true }); return;
    }
    if (viewport && !e.target.closest("button,[data-node],.wf-edge")) { e.preventDefault(); const old = { ...pan }; const move = ev => { pan = { x: old.x + ev.clientX - e.clientX, y: old.y + ev.clientY - e.clientY }; paint(); }; const up = () => { window.removeEventListener("pointermove", move); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up, { once: true }); }
  }
  function wheel(e) { e.preventDefault(); if (e.ctrlKey || e.metaKey) { const old = zoom, rect = e.currentTarget.getBoundingClientRect(), x = e.clientX - rect.left, y = e.clientY - rect.top; zoom = Math.max(.18, Math.min(1.8, zoom * (e.deltaY < 0 ? 1.08 : .92))); pan = { x: x - (x - pan.x) * zoom / old, y: y - (y - pan.y) * zoom / old }; } else { pan.x -= e.deltaX; pan.y -= e.deltaY; } paint(); }
  function keydown(e) {
    if (e.key === "Escape") { linking = null; modal = null; draw(); return; }
    if (!draft || e.target.matches("input,textarea,select") || runId) return;
    if ((e.ctrlKey || e.metaKey) && ["z", "y"].includes(e.key.toLowerCase())) { e.preventDefault(); const action = e.key.toLowerCase() === "y" || e.shiftKey ? "redo" : "undo"; host.querySelector(`[data-wf="${action}"]`)?.click(); }
    if (e.key === "Delete" || e.key === "Backspace") { e.preventDefault(); host.querySelector('[data-wf="deleteNode"]')?.click(); }
    if (["ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight"].includes(e.key) && currentNode()) { e.preventDefault(); commit(() => { const p = currentNode().position; p.x = Math.max(0, p.x + (e.key === "ArrowRight" ? 20 : e.key === "ArrowLeft" ? -20 : 0)); p.y = Math.max(0, p.y + (e.key === "ArrowDown" ? 20 : e.key === "ArrowUp" ? -20 : 0)); }); }
  }
  function poll() { clearTimeout(timer); if (!host?.isConnected || host.closest('[hidden]')) return; timer = setTimeout(async () => { if (!host?.isConnected || host.closest('[hidden]')) return; if (!busy && (section === "runs" || runId || inspector === "runs" && draft)) { try { const before = JSON.stringify(data.runs); await refresh(); if (before !== JSON.stringify(data.runs) && !host.querySelector("input:focus,textarea:focus,select:focus")) { const opened = [...host.querySelectorAll("details[open]")].map(el => el.dataset.run).filter(Boolean); draw(); for (const id of opened) host.querySelector(`[data-run="${id}"]`)?.setAttribute("open", ""); } } catch { /* keep the last view */ } } poll(); }, 2000); }
  window.KaiWorkflows = { render, canLeave: () => !dirty() || !!runId || window.confirm("Discard unsaved workflow changes?"), leave: () => { draft = null; runId = ""; clearTimeout(timer); }, isEditing: () => !!draft };
})();
